### ISSUE TITLE
Doxygen API docs omit generic procedures

### ISSUE THREAD

**Issue by l00ki** [cp2k/cp2k#1083]
Dear all,
In the new Doxygen API documentation, I can no longer find any documentation on generic procedures such as mp_sendrecv or cp_fm_to_fm which was present in the old apidoc.cp2k.org.

**Comment by oschuett** [comment]
Yes, generic procedures were the main motivation for building Apidoc. Unfortunately, it has not been maintained since the original author left. And just leaving the stale docs up didn't seem right either (#1072).

So, if somebody wants to adopt the project, I'm happy to help. The sources are here:
https://github.com/oschuett/fparse
https://github.com/oschuett/ast2doc

Until recently, I was worried about the licensing of [this file](https://github.com/oschuett/ast2doc/blob/master/makeHTML.py), but today I found on the [author's website](https://www.hoboes.com/Mimsy/hacks/object-oriented-html/) that it's apparently GPL.

However, before spending too much time on it one should reevaluate the alternatives. Maybe Doxygen can be extended or we can generate [Ford docs](https://github.com/Fortran-FOSS-Programmers/ford) alongside.

**Comment by l00ki** [comment]
That's a shame I was relying on it a lot. I'll have a look at what extending Doxygen entails.

**Comment by oschuett** [comment]
Many of the generic procedures were introduced to support multiple data types - especially in DBCSR.

In hindsight this was not the best design decision because it added a lot of complexity and in practice we only use double precision.

So, going forward we should avoid excessive use of generic procedures. For example, the new DBM and DBT libraries support only doubles.
