### ISSUE TITLE
Floating point exception FE_INVALID in grid_collocate_unittest

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1104]
The [Intel regression test](https://www.cp2k.org/static/regtest/trunk/Linux-x86-64-intel-regtest/psmp/regtest-0) fails because of a floating point exception FE_INVALID in grid_collocate_unittest.

**Comment by oschuett** [comment]
Yes, I've added a check for some floating point exceptions in 4ce1476d1f83614fefa1252d0f999b9c8796171b.

To investigate this further we'd have to trap the `SIGFPE` signal and print the [backtrace](https://www.gnu.org/software/libc/manual/html_node/Backtraces.html).

Alternatively, we could just remove the check for `FE_INVALID` - it's probably caused by some compiler optimization anyways.

**Comment by mkrack** [comment]
We should ignore that exception or downgrade it to a warning unless you think that is a serious issue. The Intel compiler did not print any notification. It seems that issue is compiler dependent, since it does not appear with GNU compiler.

**Comment by oschuett** [comment]
Yes, I think `icc -O2` implies `-fp-model=fast`, for which the [docs](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/floating-point-options/fp-model-fp.html) explicitly state that floating point exception might occur.

I think `FE_DIVBYZERO` and `FE_OVERFLOW` are the important ones and [grid_collocate_unittest](https://github.com/cp2k/cp2k/blob/master/src/grid/grid_collocate_unittest.c) is only meant as a smoke test anyways.

**Comment by mkrack** [comment]
I added -fp-model precise also to the CFLAGS (in addition to the FFLAGS) , but there is still one `FE_INVALID` in the printout. So, it is indeed better to drop that check.
