### ISSUE TITLE
Publish images to DockerHub again

### ISSUE THREAD

**Issue by ltalirz** [cp2k/cp2k#1173]
https://www.cp2k.org/download lists docker as one of the installation routes, but the [link](https://hub.docker.com/u/cp2k/) leads to a DockerHub organisation with no repositories:

![image](https://user-images.githubusercontent.com/1053245/99323370-6329d200-2872-11eb-9d35-f09de5ed9aae.png)

**Comment by oschuett** [comment]
Yes, I removed the images from DockerHub because they were violating the GPL.

While I managed to [solve](https://github.com/cp2k/cp2k/issues/790) the licensing issue of the toolchain, I have not yet gotten around to create new images.

Part of why I'm giving this low priority is that I currently don't see a real use case. Most HPC systems have GPUs these days, but we can't include Cuda due to the GPL. And most researchers can't run Docker on their workstation because it requires root permissions.

How did you intent to use the images?

**Comment by dev-zero** [comment]
> Part of why I'm giving this low priority is that I currently don't see a real use case. Most HPC systems have GPUs these days, but we can't include Cuda due to the GPL. And most researchers can't run Docker on their workstation because it requires root permissions.

Singularity, Podman and others are pointing towards root-less (and daemon-less) containerization, so not being root is only a problem when using Docker.

As for CUDA: since the CUDA libraries are required to be able to access the hardware they are usually considered a system-dependencies (like a libc, or a kernel) and can therefore be linked against in a GPL program under the "system library exception" (part of GPLv2/v3).

**Comment by mattatlincoln** [comment]
Not really a major use - but for teaching and workshops an easy to deploy container would be a very good thing.


[University of Lincoln]<http://lincoln.ac.uk/>  Dr. Matt Watkins | Associate Professor
School of Mathematics and Physics
University of Lincoln. Brayford Pool, Lincoln, Lincolnshire. LN6 7TS
tel: +44 (0)1522 835867
mattatlincoln.github.io<https://mattatlincoln.github.io/>


________________________________

                       
                        
The University of Lincoln, UK, is the Modern University of the Year in The Times and Sunday Times Good University Guide 2021. We are TEF-Gold rated and recognised for our high student satisfaction, award-winning industry links and world-leading research. Visit www.lincoln.ac.uk.  
                         
The information in this e-mail and any attachments may be confidential. If you have received this email in error please notify the sender immediately and remove it from your system. Do not disclose the contents to another person or take copies.
​
Email is not secure and may contain viruses. The University of Lincoln makes every effort to ensure email is sent without viruses, but cannot guarantee this and recommends recipients take appropriate precautions.
​
The University may monitor email traffic data and content in accordance with its policies and English law. Further information can be found at: http://www.lincoln.ac.uk/legal.

**Comment by ltalirz** [comment]
> How did you intent to use the images?

My use case was to quickly get a cp2k binary on MacOS for testing purposes.
The `brew` route first compiles gcc which takes forever... I've started looking into adding a conda build for MacOS https://github.com/conda-forge/cp2k-feedstock/pull/7

**Comment by oschuett** [comment]
> since the CUDA libraries are required to be able to access the hardware they are usually considered a system-dependencies 

Last time I chatted with Nvidia folks I got the impression that this is not the case.

> but for teaching and workshops an easy to deploy container would be a very good thing.

Fair enough. I'll have another look after the 8.1 release is out.

**Comment by iamid0** [comment]
Singularity would be a nice choice.

**Comment by alazzaro** [comment]
> Singularity would be a nice choice.

I would suggest keeping docker containers on dockerhub (singularity hub solutions are several limitations). Singularity can directly pull docker containers and use them...

**Comment by oschuett** [comment]
Done: https://hub.docker.com/r/cp2k/cp2k.
