### ISSUE TITLE
Wrong results with internal TPSS using GAPW and LSD

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1177]
GAPW (all-electron) OT CG runs for open-shell systems do not converge using the CP2K-internal TPSS implementation. On the other hand, the same runs converge with the corresponding libxc-TPSS routines. The following input should reproduce the issue. Setting ``@SET LIBXC     1`` selects the TPSS implementation from the libxc instead of the CP2k internal one.
```
@SET XCFUN     TPSS
@SET XFUN      none
@SET CFUN      none
@SET LIBXC     0
# Select libxc functionals for LIBXC 1
@IF ${LIBXC}
@SET XFUN      MGGA_X_TPSS
@SET CFUN      MGGA_C_TPSS
@ENDIF
# Set exact exchange (EXX) fraction
@SET HF        0
# Set SMOOTH to 1 for smoothing
@SET SMOOTH    0
@SET VDW       0
@SET PERIODIC  xyz
@SET PSOLVER   analytic
@SET SOLVER    OT
# Set STRESS to yes if available to check stress tensor
@SET STRESS    off
@SET GAPW      0
@SET BASIS_SET 6-31Gxx
@SET POTENTIAL ALL

# All-electron calculations require GAPW
@IF ${POTENTIAL} == ALL
@SET GAPW      1
@ENDIF

&GLOBAL
 PROJECT NO2_${XCFUN}
 RUN_TYPE debug
 PREFERRED_DIAG_LIBRARY sl
 PRINT_LEVEL medium
&END GLOBAL

&DEBUG
 DEBUG_FORCES yes
 DEBUG_STRESS_TENSOR ${STRESS}
&END DEBUG

&MOTION
 &PRINT
  &RESTART
   BACKUP_COPIES 0
  &END RESTART
  &STRUCTURE_DATA
   POSITION 1..3
   DISTANCE 1 2
   DISTANCE 1 3
   ANGLE 3 1 2
  &END STRUCTURE_DATA
 &END PRINT
&END MOTION

&FORCE_EVAL
 METHOD Quickstep
@IF ${STRESS} == on
 STRESS_TENSOR analytical
@ENDIF
 &DFT
  BASIS_SET_FILE_NAME BASIS_SET
  BASIS_SET_FILE_NAME BASIS_MOLOPT
  BASIS_SET_FILE_NAME EMSL_BASIS_SETS
  BASIS_SET_FILE_NAME GTH_BASIS_SETS
  POTENTIAL_FILE_NAME POTENTIAL
  CHARGE 0
  LSD
  MULTIPLICITY 2
  &MGRID
   CUTOFF 800
   NGRIDS 5
   REL_CUTOFF 60
  &END MGRID
  &POISSON
   PERIODIC ${PERIODIC}
@IF ${PERIODIC} /= xyz
   POISSON_SOLVER ${PSOLVER}
@ENDIF
  &END POISSON
  &PRINT
   &HIRSHFELD off
   &END HIRSHFELD
   &MULLIKEN off
   &END MULLIKEN
  &END PRINT
  &QS
   EPS_DEFAULT 1.0E-14
@IF ${GAPW}
   METHOD GAPW
   ALPHA0_H 10.0
   EPSFIT 1.0E-8
   EPSISO 1.0E-12
   EPSSVD 0.0
   EPSRHO0 1.0E-8
   LMAXN0 4
   LMAXN1 6
   QUADRATURE GC_LOG
@ENDIF
  &END QS
  &SCF
@IF ${SOLVER} == OT
   EPS_SCF 1.0E-6
   MAX_SCF 21
   SCF_GUESS atomic
   &OT on
    MINIMIZER CG
    PRECONDITIONER FULL_ALL
    STEPSIZE 0.1
   &END OT
   &OUTER_SCF on
    EPS_SCF 1.0E-6
    MAX_SCF 30
   &END OUTER_SCF
@ENDIF
@IF ${SOLVER} == TD
   ADDED_MOS 10
   CHOLESKY inverse
   EPS_SCF 1.0E-6
   MAX_SCF 300
   SCF_GUESS atomic
   &DIAGONALIZATION on
    ALGORITHM STANDARD
   &END DIAGONALIZATION
   &MIXING on
    ALPHA 0.1
    BETA  1.5
    METHOD direct_p_mixing
    NBUFFER 8
   &END MIXING
@ENDIF
   &PRINT
    &RESTART
     BACKUP_COPIES 0
    &END RESTART
   &END PRINT
  &END SCF
  &XC
@IF ${LIBXC} == 0
   &XC_FUNCTIONAL ${XCFUN}
@ENDIF
@IF ${LIBXC}
   &XC_FUNCTIONAL
@ENDIF
@IF ${XFUN} /= none
    &LIBXC
     FUNCTIONAL ${XFUN}
    &END LIBXC
@ENDIF
@IF ${CFUN} /= none
    &LIBXC
     FUNCTIONAL ${CFUN}
    &END LIBXC
@ENDIF
   &END XC_FUNCTIONAL
@IF ${SMOOTH}
   &XC_GRID
    XC_DERIV NN50_SMOOTH
    XC_SMOOTH_RHO none
   &END XC_GRID
@ENDIF
@IF ${HF} /= 0
   &HF
    FRACTION ${HF}
    &SCREENING
     EPS_SCHWARZ 1.0E-12
     EPS_SCHWARZ_FORCES 1.0E-10
     SCREEN_ON_INITIAL_P no
    &END SCREENING
    &MEMORY
     MAX_MEMORY 1000
     EPS_STORAGE_SCALING 0.1
    &END MEMORY
    &INTERACTION_POTENTIAL
     !POTENTIAL_TYPE Coulomb
     CUTOFF_RADIUS 4.0
     POTENTIAL_TYPE truncated
    &END INTERACTION_POTENTIAL
   &END HF
@ENDIF
@IF ${VDW}
   &VDW_POTENTIAL
    POTENTIAL_TYPE PAIR_POTENTIAL
    &PAIR_POTENTIAL
     !CALCULATE_C9_TERM
     PARAMETER_FILE_NAME dftd3.dat
     REFERENCE_FUNCTIONAL ${XCFUN}
     TYPE DFTD3
     VERBOSE_OUTPUT on
    &END PAIR_POTENTIAL
   &END VDW_POTENTIAL
@ENDIF
  &END XC
 &END DFT
 &PRINT
  &GRID_INFORMATION off
  &END GRID_INFORMATION
  &STRESS_TENSOR ${STRESS}
  &END STRESS_TENSOR
 &END PRINT
 &SUBSYS
  &CELL
   ABC 8.5 8.5 8.5
   PERIODIC ${PERIODIC}
  &END CELL
  &COORD
   N  2.5            2.5        2.5
   O  3.71590        2.5        2.5
   O  1.65536    3.37465        2.5
  &END COORD
  &KIND N
   ELEMENT N
   BASIS_SET ${BASIS_SET}
   POTENTIAL ${POTENTIAL}
@IF ${POTENTIAL} == ALL
   LEBEDEV_GRID 110
   RADIAL_GRID 200
@ENDIF
  &END KIND
  &KIND O
   ELEMENT O
   BASIS_SET ${BASIS_SET}
   POTENTIAL ${POTENTIAL}
@IF ${POTENTIAL} == ALL
   LEBEDEV_GRID 110
   RADIAL_GRID 200
@ENDIF
  &END KIND
  &PRINT
   &ATOMIC_COORDINATES on
   &END ATOMIC_COORDINATES
   &CELL on
   &END CELL
   &KINDS on
    BASIS_SET
    POTENTIAL
   &END KINDS
   &MOLECULES off
   &END MOLECULES
   &STRUCTURE_DATA
    POSITION 1..3
    DISTANCE 1 2
    DISTANCE 1 3
    ANGLE 3 1 2
    &EACH
     GEO_OPT 1
    &END EACH
   &END STRUCTURE_DATA
  &END PRINT
  &TOPOLOGY
   &CENTER_COORDINATES off
   &END CENTER_COORDINATES
  &END TOPOLOGY
 &END SUBSYS
&END FORCE_EVAL
```

**Comment by mkrack** [comment]
The CP2K-internal TPSS LSD routine is numerically unreliable for large density (rho) values. For instance, the output values for [e_rhoa](https://github.com/mkrack/cp2k/blob/master/src/xc/xc_tpss.F#L1534) and [e_rhob](https://github.com/mkrack/cp2k/blob/master/src/xc/xc_tpss.F#L1647) become divergent for rho values greater than 1.5 for an N atom. Such large rho values appear for the one-center densities in GAPW runs.

**Comment by fstein93** [comment]
The code itself was created by some maple script. Due to the git history, the python script is ca. 15 years old (by fawzi). The Fortran codes for the PBE and TPSS functionals were created by some python script (see tools/maple2f90/). To me, it is not clear how the actual code was written to prevent numerical instabilities. From time to time this machinery might be interesting to implement other functionals if necessary.
It would take some more time to find the problematic lines for TPSS and how to circumvent them.

Do you know whether its due to the exchange or the correlation part?

Rewriting everything numerically stable can be rather tedious. I tried something in that direction using Sympy for an LDA-based and a PBE-based functional and even there it's already quite difficult to implement it numerically stable. It might be due to Sympy because it tends to demultiply terms or missing cancelation of factors etc.

**Comment by oschuett** [comment]
Or maybe we should just dump our own XC implementations and rely entirely on libxc?

As @fstein93 pointed out we have lost the ability to re-generate those files and they got [poor test coverage](https://www.cp2k.org/static/coverage/src/xc/index.html). Furthermore, the XC functional is a natural next target for [GPU acceleration](https://gitlab.com/libxc/libxc#gpu-support-with-cuda).

**Comment by fstein93** [comment]
I would not dump our own XC implementations and completely rely on LibXC. It might be better to add a unittest comparing our implementations with LibXC implementations as proposed [somewhere else](https://www.cp2k.org/dev:todo). I am also not sure about testers using valgrind or similar tools.

Still, it does not solve the issues with our TPSS implementation. And we cannot support GPUs that way, for LibXC we had to rethink the interface anyway because LibXC expects pointers to GPU memory then.

**Comment by mkrack** [comment]
Thanks @fstein93 and @oschuett, that's the discussion I wanted to trigger. The TPSS functional is algebraically complicated and our internal version is not built like the libxc implementation in a modular manner. As far as I can tell, the exchange and the correlation part are lumped together. Either somebody is able to resolve the issue with the current internal TPSS implementation or I would also suggest **to remove the CP2K internal TPSS version** as suggested by @oschuett. There is no benefit in maintaining an unreliable functional implementation. Sure, this will further increase the dependency on libxc, but we depend on libxc anyway for all newer xc functionals, since we have stopped our own functional implementation since many years by now. Libxc has also a larger user base which decreases the probability of bugs. Who will check and maintain our own functional implementations in CP2K? The results from mGGA functionals (with TPSS as its first test candidate) have been fishy for a long time and now it turns out that the weird (TPSS) results might have been caused by a combination of several bugs.

**Comment by mkrack** [comment]
> Rewriting everything numerically stable can be rather tedious. I tried something in that direction using Sympy for an LDA-based and a PBE-based functional and even there it's already quite difficult to implement it numerically stable. It might be due to Sympy because it tends to demultiply terms or missing cancelation of factors etc.

@fstein93 Maybe, it would be better then to contribute to the libxc project?

**Comment by fstein93** [comment]
I never wanted planned to contribute my code to LibXC. It was justed interested in two functionals: A short-ranged LDA and a short-ranged PBE functional. For the LDA functional I was using an implementation by P. Gori-Giorgi which does not allow 2nd derivatives. That's why I tried to reimplement it but fortunately was implemented in LibXC recently. The short-ranged PBE functional will be implemented soon in LibXC. But Sympy has carried out strange things with the LDA functional and first tests of the PBE functional showed lots of numerical issues.

@mkrack Or what are you interested in? Basically, I agree with your idea.

**Comment by mkrack** [comment]
@fstein93 There is no special interest on my part

**Comment by oschuett** [comment]
Since the `libxc` is serving us well, I don't think we should invest in writing our own.
I agree with @mkrack that we should instead try to contribute when necessary.

@fstein93, if you are looking for an opportunity to leverage SymPy have a look at `libint`. It is very slow to compile, which calls for a JIT, and we currently don't have a good path for GPU accelerating those integrates.

**Comment by mkrack** [comment]
I will then remove the CP2K internal TPSS LSD implementation, if there are no further objections.
