### ISSUE TITLE
Inconsistent INTENT for NATOM

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1256]
Running most test cases in qs_ks_types.F line 514 the argument NATOM has inconsistent INTENT.
In its calling procedure it has INTENT(IN) while in procedure qs_subsys_get 
it has INTENT(OUT) because NATOM is updated.

I suggest to declare INTENT(INOUT) NATOM everywhere, as in
qs_subsys_types.F, cp_subsys_types.F, qs_overlap.F

**Comment by oschuett** [comment]
The intent of `natom` is defined as:
- `inout` in [get_ks_env](https://github.com/cp2k/cp2k/blob/master/src/qs_ks_types.F#L418)
- `out` in [qs_subsys_get](https://github.com/cp2k/cp2k/blob/master/src/qs_subsys_types.F#L176)
- `out` in [cp_subsys_get](https://github.com/cp2k/cp2k/blob/master/src/subsys/cp_subsys_types.F#L365)


Since these are all getter routines, I don't really see a problem.
I guess, we could change it to `out` in `get_ks_env` as well. Is that what you meant?

**Comment by vzecca** [comment]
natom is INTENT(IN) in procedure build_overlap_matrix_low in file qs_overlap.F.
This procedure at line 237 calls get_qs_env which at line 514 calls
qs_subsys_get
where natom is INTENT(OUT).

I am sorry, I was not clear enough in my first post.
It is now evident that there are inconsistent INTENT for natom.

**Comment by juerghutter** [comment]
This was my error. The call to get_qs_env was a leftover from refactoring. 
I have it deleted in the latest update.

**Comment by oschuett** [comment]
Fixed via #1264.
