### ISSUE TITLE
build system: missing details that make it difficult for user to compile CP2K

### ISSUE THREAD

**Issue by shoshijak** [cp2k/cp2k#130]
A list of small annoying details that make CP2K more cumbersome to build: 

- Users should be explicitly instructed that they need to have the environment variable `CUDA_PATH` defined if compiling with CUDA support (cf line https://github.com/cp2k/cp2k/blob/master/tools/toolchain/install_cp2k_toolchain.sh#L1071). Or this should be done by cp2k/tools/toolchain/install/setup. 
- The installation instructions (https://github.com/cp2k/cp2k/blob/master/INSTALL.md) do not make it very clear visually that the toolchain script is the recommended way to go for installing CP2K 
- The installation instructions in the repo (https://github.com/cp2k/cp2k/blob/master/INSTALL.md) do not correspond exactly to the installation instructions on the official website (https://www.cp2k.org/howto:compile and https://www.cp2k.org/howto:compile_with_cuda), make it confusing for users: should users follow the instructions in the repo? The ones on the website? What is more up-to-date?)

**Comment by oschuett** [comment]
There is a cron-job which mirrors [INSTALL.md](https://github.com/cp2k/cp2k/blob/master/INSTALL.md) to [howto:compile](https://www.cp2k.org/howto:compile). Currently, it runs once per night. Maybe I should run it more often?

The [compile_with_cuda](https://www.cp2k.org/howto:compile_with_cuda) page should now become a part of the DBCSR documentation, which could live [here](https://www.cp2k.org/dbcsr), [here](https://github.com/cp2k/dbcsr/wiki), or simply as Markdown in the repo.

Since CP2K is now (almost) free of CUDA code, the [Cuda section ](https://www.cp2k.org/howto:compile#j_cuda_optional_improved_performance_on_gpu_systems) in CP2K's `INSTALL.md` should be cleared out.  Instead we should link to the appropriate pages in DBCSR, ELPA, SIRIUS,...

> do not make it very clear visually that the toolchain script is the recommended way to go for installing

What do you have in mind? The toolchain is mentioned in the beginning of section 2.

**Comment by shoshijak** [comment]
> There is a cron-job which mirrors [INSTALL.md](https://github.com/cp2k/cp2k/blob/master/INSTALL.md) to [howto:compile](https://www.cp2k.org/howto:compile). Currently, it runs once per night. Maybe I should run it more often?

I'm sorry, it seemed to me like the two instructions weren't quite the same because of the more prominent /!\ warning signs on [howto:compile](https://www.cp2k.org/howto:compile). My bad. 
No, I don't think it is necessary to run this job more often.

**Comment by shoshijak** [comment]
> > do not make it very clear visually that the toolchain script is the recommended way to go for installing

> What do you have in mind? The toolchain is mentioned in the beginning of section 2.

I mean that when you just glance over the INSTALL.md, it is not made obvious, visually, that the toolchain script is the way to go for installing pre-requisites. 
Writing the actual instruction  for calling the toolchain there would make stand out more. I'll open a PR and you'll see what I mean.

**Comment by oschuett** [comment]
> For the time being, I would leave the documentation on how to compile DBCSR/CUDA within CP2K.

Fine with me. The downside is that then there will be some duplication (and possibly confusion) because the DBCSR-only users will also need their documentation, right?

> because of the more prominent /!\ warning signs 

Hehe, yes there is a bit of regex magic going on :-)

> I'll open a PR and you'll see what I mean.

Perfect !

**Comment by oschuett** [comment]
As you probably figured, the warning boxes are triggered by the ⚠️ emoji. In Dokuwiki we are using the [note plugin](https://www.dokuwiki.org/plugin:note). So, we could also make use of the other box types using e.g. the 💡 emoji.
