### ISSUE TITLE
Compiling cp2k 8.1 on macOS

### ISSUE THREAD

**Issue by fxcoudert** [cp2k/cp2k#1312]
We're trying to build cp2k 8.1 on macOS as part of Homebrew: https://github.com/Homebrew/homebrew-core/pull/68951

We are seeing several failures:

- `malloc.h` header, fixed by https://github.com/cp2k/cp2k/commit/4139ab6cd2d60c112964a6c75c5d52576ac49e6b (but not part of the released version)
- the latest stable libint version for CP2K (`libint-v2.6.0-cp2k-lmax-4`) fails to build with GCC 10: `Error: missing '(' before "__has_include" operand`)
- and if we fix that by moving to the libint-cp2k beta version, `make ARCH=Darwin-IntelMacintosh-gfortran VERSION=ssmp` fails with:

```
/private/tmp/cp2k-20210116-20292-1c8dsfw/cp2k-8.1/src/grid/common/grid_library.c:28:2:
error: #error "OpenMP is required. Please add -fopenmp to your C compiler flags."
```

I do not see the reason why `-fopenmp` was not added to `CFLAGS` in the darwin arch files (or BSD ones, for that matter). Are we doing something wrong, or is it a bug?

**Comment by dev-zero** [comment]
Thanks for testing and updating the package in Homebrew!

>     * `malloc.h` header, fixed by [4139ab6](https://github.com/cp2k/cp2k/commit/4139ab6cd2d60c112964a6c75c5d52576ac49e6b) (but not part of the released version)

Yeah, v8.1 was not tested on macOS it seems, but I'm working on it.

>     * the latest stable libint version for CP2K (`libint-v2.6.0-cp2k-lmax-4`) fails to build with GCC 10: `Error: missing '(' before "__has_include" operand`)

That's a GCC bug, see https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/files/gcc-10.2.0-cpp-__has_include.patch
Patch was accepted into GCC and should be part of GCC 10.3+

>     * and if we fix that by moving to the libint-cp2k beta version, `make ARCH=Darwin-IntelMacintosh-gfortran VERSION=ssmp` fails with:

That's not supported and not recommended.

> ```
> /private/tmp/cp2k-20210116-20292-1c8dsfw/cp2k-8.1/src/grid/common/grid_library.c:28:2:
> error: #error "OpenMP is required. Please add -fopenmp to your C compiler flags."
> ```
> 
> I do not see the reason why `-fopenmp` was not added to `CFLAGS` in the darwin arch files (or BSD ones, for that matter). Are we doing something wrong, or is it a bug?

This is a bug and needs to be added.

**Comment by carlocab** [comment]
>That's not supported and not recommended.

Which isn't? Using the beta version of `libint-cp2k`?

**Comment by dev-zero** [comment]
@carlocab the beta version of libint (and therefore also `libint-cp2k`) is not supported. We only support v2.6.0 of libint at the moment.

**Comment by fxcoudert** [comment]
@dev-zero I understand your position but as a result, it means cp2k is uncompilable for us with the latest version of every dependency. We won't distribute version 8.1, and wait in hope a later version does work with "everything up to date".

**Comment by dev-zero** [comment]
@fxcoudert there are several points from my side:

* Homebrew provides a compiler with a known and fixed defect. You - as a distro - could fix it quiet easily by simply pulling the (upstream accepted) patch in or stick with a version without the defect (as many Linux distros do).
* Being able to build with and returning consistent results with same performance are different things in computing codes, see our [dashboard](https://dashboard.cp2k.org/) as an example. Even across different versions of a compiler or a library we see discrepancies.
* Hence describing a beta-version of a computing library (like libint) as a "latest release" does not really make sense (see also the mess that was libxc 5.0)

Since all the other issues were solved and CP2K itself builds with gcc-10 on macOS I am closing this.
