### ISSUE TITLE
The download process of latest SIRUS 7.0.2  can not been finished

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#1369]
The download process of latest SIRUS 7.0.2  can not been finished. several hours passed, it only downloaded 15.5 MB but the size of early editon 7.0.0 is 55 MB. hen i download it from github, it is sure that the package is only 15 MB and it report an unexpected ending when tar -xvf.  I don't think the main problem is the slow connection speed of the internet. kindly, please upload the file pack to www.cp2k.org/static/downloads as soon as possible.
thks.

**Comment by oschuett** [comment]
The latest SIRUS 7.0.2 archive has a size of 55828 bytes and can be downloaded from [Github](https://github.com/electronic-structure/SIRIUS/archive/v7.0.2.tar.gz). Since we consider Github as essential infrastructure, we generally don't mirror packages from there to www.cp2k.org/static/downloads.

Please note that [redundant](https://github.com/cp2k/cp2k/issues/1283#issuecomment-781763149) and [off-topic](https://github.com/cp2k/cp2k/issues/728#issuecomment-781002274) posts help nobody. If you really can't download from Github then you should talk to your local admin. For usage questions you find a better audience at our [forum](https://www.cp2k.org/howto:forum).
