### ISSUE TITLE
Pre-commit error after shfmt (shell parser, formatter, interpreter) was added

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1371]
I get the following error log from pre-commit when I try to commit changes:

## version information
```
pre-commit version: 2.6.0
sys.version:
    3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
sys.executable: /opt/psi/Programming/psi-python36/4.4.0/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/psi/Programming/gcc/8.3.0/bin/go', 'get', 'mvdan.cc/sh/v3/cmd/shfmt@v3.2.2')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    package mvdan.cc/sh/v3/cmd/shfmt@v3.2.2: unrecognized import path "mvdan.cc/sh/v3/cmd/shfmt@v3.2.2" (parse https://mvdan.cc/sh/v3/cmd/shfmt@v3.2.2?go-get=1: no go-import meta tags ())
    
```

```
Traceback (most recent call last):
  File "/psi/home/krack/.local/lib/python3.6/site-packages/pre_commit/error_handler.py", line 56, in error_handler
    yield
  File "/psi/home/krack/.local/lib/python3.6/site-packages/pre_commit/main.py", line 372, in main
    args=args.rest[1:],
  File "/psi/home/krack/.local/lib/python3.6/site-packages/pre_commit/commands/hook_impl.py", line 217, in hook_impl
    return retv | run(config, store, ns)
  File "/psi/home/krack/.local/lib/python3.6/site-packages/pre_commit/commands/run.py", line 380, in run
    install_hook_envs(hooks, store)
  File "/psi/home/krack/.local/lib/python3.6/site-packages/pre_commit/repository.py", line 200, in install_hook_envs
    _hook_install(hook)
  File "/psi/home/krack/.local/lib/python3.6/site-packages/pre_commit/repository.py", line 83, in _hook_install
    hook.prefix, hook.language_version, hook.additional_dependencies,
  File "/psi/home/krack/.local/lib/python3.6/site-packages/pre_commit/languages/golang.py", line 83, in install_environment
    cmd_output_b('go', 'get', dependency, cwd=repo_src_dir, env=env)
  File "/psi/home/krack/.local/lib/python3.6/site-packages/pre_commit/util.py", line 157, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/psi/Programming/gcc/8.3.0/bin/go', 'get', 'mvdan.cc/sh/v3/cmd/shfmt@v3.2.2')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    package mvdan.cc/sh/v3/cmd/shfmt@v3.2.2: unrecognized import path "mvdan.cc/sh/v3/cmd/shfmt@v3.2.2" (parse https://mvdan.cc/sh/v3/cmd/shfmt@v3.2.2?go-get=1: no go-import meta tags ())
   
```
How can I fix that issue?

**Comment by oschuett** [comment]
This is a problem with the [old pre-commit](https://github.com/cp2k/cp2k/blob/master/.pre-commit-config.yaml) system. It requires you to install every tool and its dependencies locally. In this case you'll need the Go compiler to build [shfmt](https://github.com/mvdan/sh#shfmt). So, `apt-get install golang` should do the trick.

Alternatively, you could just switch to my [new precommit](https://github.com/cp2k/cp2k/tree/master/tools/precommit#install-git-hook) system, which works out-of-the-box by running the exotic tools in the cloud.

**Comment by dev-zero** [comment]
> This is a problem with the [old pre-commit](https://github.com/cp2k/cp2k/blob/master/.pre-commit-config.yaml) system.

Please stop spreading FUD. There is no `old` or `new` system. `pre-commit` allows to run things decentralized, locally, without uploading anything to the cloud (especially not files never intended to be submitted) and is used by millions of projects, while your `precommit` does it transparently in the cloud (one could almost say covertly since it also uploads things not added to the git index and it doesn't request consent from the user to do so).

> It requires you to install every tool and its dependencies locally. In this case you'll need the Go compiler to build [shfmt](https://github.com/mvdan/sh#shfmt). So, `apt-get install golang` should do the trick.

Also here only partially correct: of course `pre-commit` needs to have the tools locally, but all dependencies until now were automatically and transparently installed in isolated environments and did not require user interaction. Yes, unfortunately for running `shfmt` it seems that currently one has to provide a `go` interpreter.
One way is to install it on the system, another would be to use [asdf](https://asdf-vm.com) and it's [golang plugin](https://github.com/kennyp/asdf-golang) to manage a separate installation.

**Comment by dev-zero** [comment]
@mkrack it seems you have `go` available as part of the PSI programming env, as `gcc-go` (rather than the "original" `go`). I've verified here that a gcc-provided `go` should also work, but I only had `gcc-go-10` available for testing. Could you verify whether there is a `$GOROOT` environment variable set? This may interfere with things it seems. If there is a `/usr/bin/go` available it might also help to try this one instead.

If you want to debug it (e.g. without `pre-commit`), try running `GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt@v3.2.2` on the command line.

**Comment by mkrack** [comment]
@oschuett and @dev-zero many thanks for your feedback.

@dev-zero I load the module for gcc 8.3.0 which provides also go version go1.10.3 gccgo and no environment variable `$GOROOT` or even `$GO*` is defined, but `go env` returns values. There is no /usr/bin/go installed. It seems there are [remedies](https://medium.com/@dayakar88/a-guide-to-solve-no-go-import-meta-tags-for-private-repositories-with-go-modules-6b9237f9c9f) for the `no go-import meta tags ()` error, but I did not go into that further and I am not sure if that will solve the issue.

Finally, I bypassed the pre-commit checks using the `-n` flag and just committed after `make pretty` leaving all further checks to the PR step which simplifies my workflow.
