### ISSUE TITLE
Warning about ELPA GPU kernel being available on non-CUDA architecture

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1503]
With the current master at d8b6a4f63f82cb322eb7bac51ef45b9f493cedee I get the following warning after building with the toolchain on a non-CUDA system with `PREFERRED_DIAG_LIBRARY ELPA`:

```
 *** WARNING in fm/cp_fm_elpa.F:218 :: ELPA GPU kernel is available, but ***
 *** not enabled automatically.                                          ***
```

This is wrong.

**Comment by mkrack** [comment]
Though a regression tester run on daint-gpu (CRAY-XC50) shows no wrong or failed tests, there are still many warnings and MPI errors printed of the following kind:
```
 *** WARNING in fm/cp_fm_elpa.F:218 :: ELPA GPU kernel is available, but ***
 *** not enabled automatically.                                          ***

 MPI ERROR occured during mpi_comm_free for row communicator: Invalid communicator, error stack:
PMPI_Comm_free(143): MPI_Comm_free(comm=0x7fffffff2570) failed
PMPI_Comm_free(93).: Invalid communicator
 Cannot destroy the ELPA object!
 This is a critical error!
 This might lead to a memory leak in your application!
 But you do not check the error codes!
```

**Comment by oschuett** [comment]
The GPU warnings are triggered [here](https://github.com/cp2k/cp2k/blob/ec5a166d3b9bfcb1c3a7c7238ba3425f0d43798d/src/fm/cp_fm_elpa.F#L217). I assumed `elpa_obj%can_set("gpu", 1)` was the right way to check for GPU support, but looking at what is presumably the [implementation](https://github.com/marekandreas/elpa/blob/377ac3b82b87b951c4d0c3d5f360c13ff5f1d40d/src/elpa_index.c#L911) that seems to not be the case. Since we did not yet get ELPA+GPU to work anyways, I'll just remove those warnings.

It's strange that the warnings about leaked ELPA objects persist. I expected them to turn into aborts after https://github.com/cp2k/cp2k/commit/dceca619d364c6143939a7b78efb5aa41d85f686.
