### ISSUE TITLE
What is the precision of CP2K

### ISSUE THREAD

**Issue by ipe-zhangyz** [cp2k/cp2k#1532]
In the benchmarks/QS/check-release-comparison.py file there is a note: Run the benchmark in this directory with multiple combinations of OpenMP threads and MPI ranks, calculate the average of the final total energies, the variance and checks that each energy is within 1e-10 of the average. Does this mean that, at least for the benchmarks in the benchmarks/QS directory, the precision of CP2K is 1e-10? I mean, for example, the results from CP2K executables using different compilers, different mathlabs, or even running on different kinds of processors(CPU/GPU), should be within 1e-10 of each other? If not, what precision should CP2K be of, at least for the tests in that directory?
Thanks!

**Comment by hfp** [comment]
If there is no physical reference available (or known at all) like a value that can ultimately judge correctness of a solution, it is even unknown what value is "more correct" when comparing two results. A version of CP2K that consists of sequential debug code rather than highly optimized or parallelized ("production code") is typically accepted as producing reference results ("likely more correct"). Even this is questionable, e.g., although parallelized code can exhibit run-to-run variance (an unwanted property), it can still exhibit better numerical bounds at least when strong-scaled like smaller working sets (think of a reduction/sum of values running over a large set of numbers: it is more likely less accurate when compared to a hierarchical reduction over smaller individual sets).

> The `cp2k/tests` directory or the many `TEST_FILES` in particular contain numerical bounds of every test case. Acceptable deviations (margins) are collected over years and stem from mixed sources like physical correct references (publications), results from other programs that are "known to be good" (publications or contributed results), or simply from sequential debug variants of CP2K.

A domain expert can better advise on acceptable margins for properties as calculated by CP2K, if you have a specific concern. Please share details about the background of your issue. Please also note, "correct results" also depend on the method used to calculate a certain property (in case there are multiple/different methods available). A well-known analogy for such kind of correctness is the ladder from the Hartree world to the "heaven of chemical accuracy" (see [here](https://www.google.com/search?q=ladder+from+the+Hartree+world+to+the+heaven+of+chemical+accuracy&tbm=isch) for some metaphorical depictions).

**Comment by ipe-zhangyz** [comment]
Thank you for your reply! I just want to judge if my compilation of CP2K from the source is correct. I got different results from different machines. For example, on one machine with intel CPU, the last ENERGY of benchmarks/QS/H2O-256.inp is -4404.232315960794949, on another machine which has AMD CPU, the last ENERGY of the same benchmark is -4404.232287203202759. I don't know if this is OK. I've tried the regression test. Unfortunately, among the over 3000 tests, both the two machines have 10 to 20 tests failed. Maybe they both have some problems.

**Comment by ducryf** [comment]
cp2k comes with a large number of tests you can use to check whether the executable compiled correctly or not. You can either run the tests directly after compiling cp2k with

make -j ARCH=xxx VERSION=xxx test 

or at a later time with

tools/regtesting/do_regtest -quick -version xxx -arch xxx

Of course you have to replace the xxx with the actual arch and version. At the end you should see a summary like (ideally):
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 3437
Total number of   tests 3437

For more information please have a look at https://www.cp2k.org/dev:regtesting

**Comment by ipe-zhangyz** [comment]
Thank you! I have run the regression tests. Some of the tests get FAILED or WRONG results. I'd try to figure out what's going wrong.

**Comment by ipe-zhangyz** [comment]
Thank you! I have run the regression tests. Some of the tests get FAILED or WRONG results. I'd try to figure out what's going wrong.

**Comment by hfp** [comment]
Have a look at CP2K's ARCH directory and pick a suitable ARCH-file and customize accordingly. An alternative is to build CP2K using its toolchain. The latter is meant to be more reproducible since it even builds the compiler and other foundational bits. Incorrect results from the regtest (WRONG or even FAILED) can stem from exotic compilers or flags, or from incorrectly build dependencies. For further help or analysis, you could visit CP2K's user forum and perhaps post your ARCH-file so that somebody can take a look.

**Comment by ipe-zhangyz** [comment]
OK, thanks for your advice!
