### ISSUE TITLE
Cube I/O MPI Acceleration

### ISSUE THREAD

**Issue by nholmber** [cp2k/cp2k#16]
MPI I/O accelerated cube file writing/reading routines have been enabled as default since CP2K version 6.1 on supported systems. An input option to disable MPI I/O has not been provided thus far. 

Referring to the details in this Google groups [post](https://groups.google.com/forum/#!topic/cp2k/RgsNKmQtVXw), MPI I/O does not appear to improve I/O performance across all systems. I added a flag (`ENABLE_MPI_IO` in [GLOBAL](https://manual.cp2k.org/trunk/CP2K_INPUT/GLOBAL.html) section) to disable MPI I/O in commit b91fef267be208dd1fc4bc2acadc259e97af108c as a consequence. MPI I/O is still enabled by default. We can reevaluate this choice later on based on user feedback. 

I have included a set of quickly-running [inputs](https://github.com/cp2k/cp2k/files/2366497/test_files.zip) as attachments for benchmark purposes. Two input files are provided which test the effects of using MPI I/O in writing and reading cube files. The system size and planewave cutoff are both kept modest so that the input files can be run on 1 MPI process. 

My timing results are included below, which were obtained on two different machines that are described further below. Even in this small system, a clear improvement due to MPI I/O is evident in the results on the reported machines.  

**Write 2 cube files (`energy_frag_a.inp`)** on *Cray XC40* (`grep "pw_to_cube" output_file.out`)

|  Number of MPI processes  |  Parallel (s) |     Serial (s) |
|:---:|:-------------:|:--------------:|
| 1   |         5.717 |          5.572 |
| 2   |         5.529 |          5.636 |
| 4   |         2.926 |          6.121 |
| 8   |         1.562 |          5.894 |
|12   |         1.156 |          6.071 |
|24   |         0.656 |          6.152 |

**Read 4 cube files (`energy_cdft.inp`)** on *Cray XC40* (`grep "cube_to_pw" output_file.out`)

|  Number of MPI processes   |  Parallel (s) |     Serial (s) |
|:---:|:-------------:|:--------------:|
| 1   |         7.965 |          7.978 |
| 2   |         4.644 |          8.078 |
| 4   |         2.511 |          8.535 |
| 8   |         1.378 |          9.051 |
|12   |         1.036 |          9.479 |
|24   |         0.650 |         10.951 |

**Write 2 cube files (`energy_frag_a.inp`)** on *local workstation* (`grep "pw_to_cube" output_file.out`)

|  Number of MPI processes  |  Parallel (s) |     Serial (s) |
|:---:|:-------------:|:--------------:|
| 1   |         4.038 |          4.088 |
| 2   |         5.919 |          4.665 |
| 4   |         3.933 |          4.755 |
| 6   |         4.518 |          6.238 |
| 8   |         3.774 |          8.043 |

**Read 4 cube files (`energy_cdft.inp`)** on *local workstation* (`grep "cube_to_pw" output_file.out`)

|  Number of MPI processes |  Parallel (s) |     Serial (s) |
|:---:|:-------------:|:--------------:|
| 1   |         6.010 |          5.972 |
| 2   |         5.585 |          6.039 |
| 4   |         3.876 |          6.500 |
| 6   |         4.299 |         10.777 |
| 8   |         3.908 |         11.103 |

**Machine details**
- Cray XC40
  - Each node consists of 2 x 12-core Intel Xeon E5-2690v3 (Haswell), 64 GB Memory
  - Aries interconnect, Lustre filesystem
  - Compilation environment: gfortran 6.2.0, cray-mpich 7.5.1, cray-libsci 16.11.1
- Local machine
  - 1 x 4-core Intel Xeon E3-1230 v5
  - Mixed ext4/nfs file system (test data was read/written to a nfs disk, but results consistent also on ext4) 
  - gfortran 5.4, openmpi 1.10.2, scalapack from libatlas 3.10.2 installed via Ubuntu 16.04 repos

**Running the benchmark simulations**
- MPI I/O can be enabled/disabled by adjusting the value of the variable `USE_MPI_IO` in the input files.
- The timing simulations on the local machine were run using (MPI I/O disabled)
`for n in 8 6 4 2 1; do mpiexec -np $n $CP2K_PATH/cp2k.popt energy_frag_a.inp > energy_frag_a_nompi_np${n}.out; done &`
`for n in 8 6 4 2 1; do mpiexec -np $n $CP2K_PATH/cp2k.popt energy_cdft.inp > energy_cdft_nompi_np${n}.out; done &`
where  `$CP2K_PATH` is the path to the CP2K binary

**Comment by mkrack** [comment]
Hi Nico

I have run your benchmark cases on one of our local PSI cluster nodes:

- Model name: Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
- Thread(s) per core: 1
- Core(s) per socket: 14
- Socket(s): 2
- I/O to local disk (xfs, RedHat 7.4)
- gfortran 6.4.0, mpich 3.2.1

I can confirm your observation that the use of MPI I/O is quite beneficial:

**Write 2 cube files (`energy_frag_a.inp`)**

| Number of MPI processes | Parallel (s) | Serial (s) |
|:---:|:-------------:|:--------------:|
|  1  |  5.511 |  5.161 |
|  2  |  6.073 |  5.645 |
|  4  |  3.142 |  5.526 |
|  8  |  1.729 |  6.483 |
| 12  |  1.314 |  6.521 |
| 24  |  0.758 |  7.296 |

**Read 4 cube files (`energy_cdft.inp`)**

| Number of MPI processes | Parallel (s) | Serial (s) |
|:---:|:-------------:|:--------------:|
|  1  |  7.538 |  7.448 |
|  2  |  4.459 |  7.654 |
|  4  |  2.283 |  7.904 |
|  8  |  1.248 |  9.270 |
| 12  |  0.946 | 10.286 |
| 24  |  0.560 | 13.021 |

Cheers

Matthias

**Comment by OndrejMarsalek** [comment]
Thank you for the detailed numbers. Here are my results, all from the cluster where I originally observed the slowdown that I reported. This is a small cluster with a filesystem that is a simple RAID 6 array mounted over NFS on all the nodes. This is far from ideal for heavy I/O, but has been great for AIMD with CP2K, including regularly writing cube files. I would like to keep using it this way and thus benchmark on the NFS filesystem, rather than local disk or RAM disk. The nodes have dual socket RYZEN CPUs with a total of 32 physical cores per node, but I don't think it matters much for this purpose.

For the benchmark I see the same benefits of MPI I/O, at least for higher numbers of cores:

**Write 2 cube files (`energy_frag_a.inp`)**

Number of MPI processes | Parallel (s) | Serial (s)
-- | -- | --
 1 |  7.804 | 7.710
 2 | 12.215 | 8.261
 4 |  6.805 | 8.611
 8 |  4.735 | 8.759
16 |  2.811 | 8.881
32 |  2.146 | 8.405

However, when I go closer to my original system, I see the problem come back - MPI I/O is slower across the board. For this, I take `tests/QS/benchmark/H2O-64.inp` for the CP2K repository, run it as a single point energy calculation and add a write of the electron density cube file (stride 1).

Number of MPI processes | Parallel (s) | Serial (s)
-- | -- | --
 1 |  1.831 | 1.861
 2 | 10.291 | 1.973
 4 |  9.953 | 1.932
 8 |  7.490 | 1.944
16 |  7.282 | 2.012
32 |  7.939 | 1.927

So you can see that in this particular situation, I certainly do benefit from the ability to turn MPI I/O off. For other systems I've tried the ratio of the two was even higher. I have no doubt that with a better filesystem, the issue would go away, but I am otherwise happy with the current setup and would like to keep using it without a performance penalty.

As for the default, I don't mind at all that being MPI I/O on, as I am sure that in the typical use case on a more serious machine it is beneficial even for other systems.

Many thanks for including the setting, @nholmber, and I certainly hope that it stays.

**Comment by schulkov** [comment]
Hi Ondřej.

Your benchmark results are in line with my experience with NFS, which is not optimal for simultaneous write operations. In case of a small amount of data being written from a single computational node, you can notice some benefits from using parallel MPI I/O. This is because the Linux kernel caches data and rearranges I/O operations in the most optimal order. Parallel performance degrades significantly when the amount of data is large enough, so it is no longer fit into I/O buffer either on the computational node or NFS server. This is also true when different parts of a file are updated from several nodes at the same time.

**Comment by nholmber** [comment]
The flag to optionally disable MPI I/O seems to be an adequate solution. I am closing this issue.
