### ISSUE TITLE
Adding GTH pseudopotentials into repository

### ISSUE THREAD

**Issue by miroi** [cp2k/cp2k#1624]
Hello,

there was a work https://doi.org/10.1021/acs.jctc.1c00026  which generated GTH pseudopotentials for actinides.

The current file https://github.com/cp2k/cp2k/blob/master/data/GTH_POTENTIALS is up to Rn, plus U. Would be good to extend this file with new  pseudopotentials.

**Comment by oschuett** [comment]
Thanks for the link!

Yes, it would be nice to add them to our library. It seems the required lines could be copied verbatim from the supporting information.

However, I'm not sure about the licensing situation here? Maybe somebody knows one of the authors?

**Comment by juerghutter** [comment]
Hi

you can find the by the authors adjusted version of these PP
in the data directory within the file 
AcPP1_POTENTIALS.

There is also similar PP for the Lanthanide series in
LnPP1_POTENTIALS

best regards

Juerg Hutter

--------------------------------------------------------------
Juerg Hutter                         Phone : ++41 44 635 4491
Institut für Chemie C                FAX   : ++41 44 635 6838
Universität Zürich                   E-mail: ***@***.***
Winterthurerstrasse 190
CH-8057 Zürich, Switzerland
---------------------------------------------------------------

-----"Miro Iliaš" ***@***.***> wrote: -----
To: "cp2k/cp2k" ***@***.***>
From: "Miro Iliaš" ***@***.***>
Date: 08/11/2021 10:15PM
Cc: "Subscribed" ***@***.***>
Subject: [cp2k/cp2k] Adding GTH pseudopotentials into repository (#1624)


 Hello,
 there was a work https://doi.org/10.1021/acs.jctc.1c00026  which generated GTH pseudopotentials for actinides.
 The current file https://github.com/cp2k/cp2k/blob/master/data/GTH_POTENTIALS is up to Rn, plus U. Would be good to extend this file with new  pseudopotentials.
  —
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by miroi** [comment]
Ah, indeed, the file https://github.com/cp2k/cp2k/blob/master/data/AcPP1_POTENTIALS  is in the master version, not in the 8.2.0 version which I have. At least one can update the paper reference in https://github.com/cp2k/cp2k/blob/master/data/AcPP1_POTENTIALS#L4-L5 .

And after, this ticket can be closed.
