### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by bty038** [cp2k/cp2k#2059]
I'm compiling cp2k on my window11*64bit computer according to the https://www.cp2k.org/howto:compile_on_windows_with_cygwin shows. and it shows 

```
/cygdrive/d/cp2k/cp2k-9.1/src/common/memory_utilities_unittest.F:10:8:

   

10 |    USE memory_utilities,                ONLY: reallocate
      |        1
Fatal Error: Cannot open module file ‘memory_utilities.mod’ for reading at (1): No such file or directory
compilation terminated.
make[1]: *** [/cygdrive/d/cp2k/cp2k-9.1/Makefile:531: memory_utilities_unittest.o] Error 1
make: *** [Makefile:158: all] Error 2
```

  Since I'm a novice and I have no idea about that. Does anyone know the reason? Appreciate any of your advice and thanks for the help.

**Comment by oschuett** [comment]
Compiling CP2K on Windows was never officially supported. Nevertheless, some people managed to do it in the past using Cygwin. Apparently, that howto is now outdated. So, if you manage to get it to work again, feel free to post an update.

Otherwise, we should probably remove the wiki page. I guess, with the advent of [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) Cygwin is obsolete anyway?

**Comment by alazzaro** [comment]
Added a banner in the wiki, see https://www.cp2k.org/howto:compile_on_windows_with_cygwin

**Comment by oschuett** [comment]
Maybe this helps: https://github.com/cp2k/cp2k/issues/2209#issuecomment-1217926267

**Comment by dev-zero** [comment]
There is also the possibility of cross-compiling a Windows binary from Linux with mingw (without MPI):

https://github.com/cp2k/cp2k/blob/master/arch/Linux-x86-64-mingw64-minimal.sopt

Hence you should be able to build CP2K with just the mingw stack rather than a full Cygwin.
