### ISSUE TITLE
Compiled PSMP too slow and fails the tests

### ISSUE THREAD

**Issue by hyhuang00** [cp2k/cp2k#2074]
I have installed cp2k v9.1 recently using the toolchain method, with openmpi v4.1 and without sirius. Previously, I have also tried to use `--with-openmpi=install`, but my local openmpi is of v2.1, which leads to some illegal instruction error when compiling.

Here is the exact command I used to build the toolchain:
`/bin/bash install_cp2k_toolchain.sh --with-libxsmm=install --with-fftw=install  --with-openmpi=install --with-sirius=no --with-elpa=no`

After `source ./install/setup`, I compile cp2k using the following command:
`make -j 32 ARCH=local VERSION="ssmp psmp"`

The compiled ssmp version successfully passed all the tests, but the psmp version fails due to lots of timeouts and wrong results. The machine I used has Intel Xeon Gold 6226 Processor, and I utilized 32 cores and 128 GB output. Following #2048, I used the following command:
`make ARCH=local VERSION="psmp" test TESTOPTS="--maxtasks 8"`. Changing the maxtasks option to a larger number, say 32, doesn't makes the test any faster. 

Here is a summary of the output:

```
----------------------------- Settings ---------------------------------
MPI ranks:      2
OpenMP threads: 2
GPU devices:    1
Workers:        8
Timeout [s]:    400
Work base dir:  /usr/project/xtmp/hyhuang/xiaodai/cp2k/cp2k-9.1/regtesting/TEST-local-psmp-2022-04-18_15-38-32
MPI exec:       ['mpiexec']
Keepalive:      False
Debug:          False
ARCH:           local
VERSION:        psmp
Flags:          omp,libint,fftw3,libxc,parallel,mpi3,scalapack,cosma,xsmm,spglib,libvori,libbqb
------------------------------------------------------------------------

......
    TMC_NPT_2pot.inp                                                     WRONG RESULT (  59.61 sec)
    TMC_NPT_2pot_2.inp                                                   WRONG RESULT (  64.35 sec)
......
------------------------------- Timings --------------------------------
Plot: name="timings", title="Timing Distribution", ylabel="time [s]"
PlotPoint: name="100th_percentile", plot="timings", label="100th %ile", y=400.07, yerr=0.0
PlotPoint: name="99th_percentile", plot="timings", label="99th %ile", y=400.07, yerr=0.0
PlotPoint: name="98th_percentile", plot="timings", label="98th %ile", y=400.06, yerr=0.0
PlotPoint: name="95th_percentile", plot="timings", label="95th %ile", y=400.06, yerr=0.0
PlotPoint: name="90th_percentile", plot="timings", label="90th %ile", y=400.04, yerr=0.0
PlotPoint: name="80th_percentile", plot="timings", label="80th %ile", y=400.04, yerr=0.0

------------------------------- Summary --------------------------------
Number of FAILED  tests 51
Number of WRONG   tests 2
Number of CORRECT tests 30
Total number of   tests 83

Summary: correct: 30 / 83; wrong: 2; failed: 51; 68min
Status: FAILED

```

It seems like the mpi ranks, workers and threads are not following my command. How can I control the number of processes and threads to use for cp2k? What is potentially going wrong here? Shall I recompile the code with sirius and elpa? I have trouble in compiling elpa and I don't know how to solve it as well.

**Comment by oschuett** [comment]
Sorry for the late reply. First off, this issue is very well written!

The `--maxtasks` does not change the number of MPI ranks or OpenMP threads - it only controls how many test directories are being run in parallel, ie. the number of workers: https://github.com/cp2k/cp2k/blob/04bdf036884d4c5df52d312d88b8cb8a9f3cd44d/tools/regtesting/do_regtest.py#L198

So, `make ARCH=local VERSION="psmp" test TESTOPTS="--maxtasks 8"` should give you the following:

```

----------------------------- Settings ---------------------------------
MPI ranks:      2
OpenMP threads: 2
GPU devices:    0
Workers:        2
Timeout [s]:    400
...
------------------------------------------------------------------------
```

Unfortunately, it's very hard to guess why you are seeing wrong results and timeouts without more information. Maybe you could add `--maxerrors 9999` to get a complete picture of which tests are failing and which one are passing. Also, it won't hurt to run it a few times to ensure that the failures are reproducible.

**Comment by hyhuang00** [comment]
Thank you for your reply! I passed the make test by changing some configuration I was using, but I am not sure if I really solved all the problems I have and my CP2K should work as normal, so I will post my "solution" here and check whether I found the real bottleneck.

I was running these experiment on a slurm managed cluster. Originally, I was using 2 nodes with the following setup:

```
#SBATCH --ntasks-per-node=32
#SBATCH --nodes=2
```
And these options gives me the incorrect output above. Following the advice from a lab consultant, I changed my setting to
```
#SBATCH --ntasks-per-node=16
#SBATCH --nodes=4
```
which utilizes 4 nodes, each with 16 processes. This gives me the correct output:
```
------------------------------- Summary --------------------------------
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 3676
Total number of   tests 3676

Summary: correct: 3676 / 3676; 122min
Status: OK
```
I am wondering why the number of tests has increased significantly, and why adding just two nodes leads to such a significant speedup. Is that because I initialized less processes on each node so that each thread can occupy one core at a time? Shall I always ensure N*M equals to the number of cores I have on a node, where N is the number of openMP thread set by  `export OMP_NUM_THREADS=N` and M is the number of processes set by `#SBATCH --ntasks-per-node=M`?

**Comment by zc62** [comment]
@hyhuang00 
> I am wondering why the number of tests has increased significantly

This is because there are this many tests, but in your previous case, the test will abort when more than 50 failed runs are detected. That is why `--maxerrors 9999` was recommended to you.

> and why adding just two nodes leads to such a significant speedup

This is indeed confusing. From https://www.cp2k.org/dev:regtesting I think the correct command should be `make ARCH=local VERSION="psmp" TESTOPTS+="--mpiranks 32 --ompthreads 2" test`, for example, if you are using 64 cores (32x2 or 16x4 in your case) and have `export OMP_NUM_THREADS=2` in your job script. ~The product should be the number of cores, and how you divide them is subject to further tests to optimize the speed (they don't necessarily tie to how you partition the cores. They can even be `"-mpiranks 8 -ompthreads 8"`).~

~The above controls how the psmp version runs each task, and the `-j` parameter for `make` (in principle) will run different tasks in parallel. For example, `make -j4 ARCH=local VERSION="psmp" TESTOPTS+="--mpiranks 4 --ompthreads 4" test` is also for 64 total cores, but 4 different tasks running in parallel, and each task uses 4 mpi processors, and each mpi processor will spawn 4 openmp threads. However, when I use `-j`, the log tells me that `make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.`. Not entirely sure if this really works. I suppose this warning is only for inner make, as suggested by `make[3]`, thus the main make task is in parallel.~

~I actually have difficulties in passing the tests. Is there any trick to pass the tests? Compiler choice? Intel or gfortran? Any special compiler flags? Like `-fp-model precise`?~

EDIT: I tried gfortran 11.1, the test passed. ~Is there a way to make intel compiler 19.1.3 work?~
EDIT2: intel compiler does work, as long as I do not link to the libraries I built. I need to rework the library compilation then.

**Comment by zc62** [comment]
Oh, I should have seen what oschuett posted about `--maxtasks` earlier. What I wrote about `make -j` is completely wrong. `make -j` simply does not work, and the number of workers is determined by `maxtasks`. The thing I missed is that `maxtasks` by default is calculated by CPU number, not the total number of cores the slurm/pbs job requested. So the refined command for 64 total cores might look like:
```
make ARCH=local VERSION="psmp" TESTOPTS+="--mpiranks 32 --ompthreads 2 --maxtasks 64" test
```
or
```
make ARCH=local VERSION="psmp" TESTOPTS+="--mpiranks 2 --ompthreads 2 --maxtasks 64" test
```
such that it automatically has 64/2/2=16 workers.

**Comment by mkrack** [comment]
`make ARCH=local VERSION="psmp" TESTOPTS+="--mpiranks 2 --ompthreads 2 --maxtasks 64" test`
using 2 MPI ranks per test case looks like the proper choice.

**Comment by zc62** [comment]
It happened to me that test `QS/regtest-negf-fft/li_chain_kp` got timed out (more than 400 seconds) if I only use 2 mpi ranks x 2 openmp threads. Not sure what happened. Even ssmp version only took 50+ seconds. Passed that test with more mpi ranks. Maybe just some strange things and re-running with 2 mpi ranks would have worked. Now I kind of understand why mpi=2 omp=2 max=num_cpu is default. In principle, as long as the job is submitted to a full node, no `TESTOPTS` is needed and everything just works.

Is it normal to see psmp version fail some tests? Even if I got gfortran/intel ssmp pass the tests with zero fail/wrong, I still get some fail/wrong with gfortran+openmpi and intel+openmpi. No optional libraries except MKL (and FFTW inside MKL) are linked.

**Comment by oschuett** [comment]
Maybe related to #2103?

**Comment by oschuett** [comment]
This seems to have been resolved.
