### ISSUE TITLE
Update CDFT howto for new Hirshfeld force implementation

### ISSUE THREAD

**Issue by chrisahart** [cp2k/cp2k#2113]
I would like to update the CDFT howto (https://www.cp2k.org/howto:cdft) to reflect the newly implemented Hirshfeld CDFT forces (https://github.com/cp2k/cp2k/pull/2111). 

Attached is a folder containing: pdf of the suggested changes, as well as a .html file with these changes. 
[howto_cdft.zip](https://github.com/cp2k/cp2k/files/8709266/howto_cdft.zip)

**Comment by alas-go** [comment]
It is very good. 

some warnings produced on Ubuntu22.04.
Post it here just for your information and references.
[warnings20220518.txt](https://github.com/cp2k/cp2k/files/8712213/warnings20220518.txt)

**Comment by hfp** [comment]
Also, [CP2K's Dashboard](dashboard.cp2k.org/) shows some issues since this PR:

* https://storage.googleapis.com/cp2k-ci/dashboard_conventions_report.txt  
  qs_cdft_methods.F: 'dr_pw[0]' is used uninitialized [-Wuninitialized]
  qs_cdft_methods.F: 'dr_pw[1]' is used uninitialized [-Wuninitialized]
  qs_cdft_methods.F: 'origin[0]' is used uninitialized [-Wuninitialized]
  qs_cdft_methods.F: 'origin[1]' is used uninitialized [-Wuninitialized]

Perhaps unrelated:
* https://www.cp2k.org/static/regtest/trunk/CRAY-XC40-gnu/11.2.0-mpich-psmp/regtest-0
* https://storage.googleapis.com/cp2k-ci/dashboard_hip-pascal_report.txt

**Comment by chrisahart** [comment]
Thank you both for letting me know, I have fixed the initialization warnings in a new pull request https://github.com/cp2k/cp2k/pull/2116

**Comment by chrisahart** [comment]
In regards to the suggested changes to the CDFT howto, do you know who I should contact regarding this?

**Comment by oschuett** [comment]
Sorry for the late reply. I created you a wiki account. You should have received an email with the credentials.

**Comment by chrisahart** [comment]
Great, thank you for your help. I have made the proposed changes.
