### ISSUE TITLE
Consider converting the build system to fpm, fortran package manager

### ISSUE THREAD

**Issue by jerryd** [cp2k/cp2k#2126]
I have been hearing a lot of success stories around using fpm to build applications.  Although I have not tried converting a project, it is my understanding that it is fairly easy to do and powerful.  I will try to explore this a little, but those most familiar with the dependencies will know best.

**Comment by oschuett** [comment]
Thanks for sharing. However, I don't think FPM is well suited as build system for CP2K because it's not a pure Fortran project. 

The current majority opinion is that we should migrate to CMake. However, since that is a huge undertaking we keep using GNU Make for the time being. Some folks have also suggested that we go straight to [Meson](https://mesonbuild.com/), which seems to be [new cool kid](https://gms.tf/the-rise-of-meson.html) in town.

See also this recent dicussion: https://github.com/cp2k/cp2k/discussions/1989
