### ISSUE TITLE
Supporting COSMA on AMD GPUs

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#2201]
The latest COSMA release adds support for AMD GPUs. This will be relevant for hardware like LUMI.

**Comment by oschuett** [comment]
Unfortunately, it's still difficult to get access to AMD GPUs because they are not available in the public clouds.
Hence, I think the computing centers have to step up. Essentially, I see two possibilities:

1. They could contribute a nightly tester to the dashboard and have someone from their staff investigate failures.
2. They could provide access to a machine that we can hook into our CI. While it won't have to be a dedicated machine, we'd need permissions to run un-reviewed code inside a Docker container. This would enable our developers to investigate problems on their own.

**Comment by alazzaro** [comment]
I'm testing on my side the dashboard on AMD hardware (once per week?). 
I think the best solution is to go for the solution 1. and set the tests on LUMI, just like we are doing on Piz Daint. I don't think solution 2. is easy implementable, but it can be something to request...
@fstein93 I think you will have access to LUMI at some point, so we can bring back this discussion by then...

**Comment by fstein93** [comment]
I added the support for COSMA's HIP backend. So, this issue is solved for now.
