### ISSUE TITLE
add new keyword

### ISSUE THREAD

**Issue by andy90** [cp2k/cp2k#2220]
Hi, I want to add a new keyword to the DFT section. I suppose I should modify the create_dft_section subroutine in the input_cp2k_dft.F file. Is that the only place I need to modify?

**Comment by fstein93** [comment]
In order to add a new keyword, you have to add the keyword to the respective section (in your case input_cp2k_dft.F), extract the keyword from the input to the given data type (in your case probably the dft_control_type in cp_control_types.F) and finally, the new functionality related to this keyword (file depends on the functionality).
