### ISSUE TITLE
DBT unit tests fail using the DPC++/C++ oneAPI Intel compiler (icpx/icx)

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#2692]
The DBT unit tests fail using the current DPC++/C++ Intel oneAPI compiler (icpx/icx) version (2023.0.0) as shown by PR #2691. Consequently, tests using DBT are failing as well.

**Comment by oschuett** [comment]
According to the [report](https://storage.googleapis.com/cp2k-ci/run-cp2k-intel-psmp-306576a4_report.txt) it failes at https://github.com/cp2k/cp2k/blob/0165da4645489888fae55c9cbb9ccbdcebf313e1/src/dbm/dbm_multiply.c#L312

That is a very basic sanity check at the very beginning of `dbm_multiply`. So, my guess would be that something more fundamental is at fault here. Maybe the ISO_C_BINDINGS between the old `ifort` and the new `icx`?

To get started, I would track the variables `nrows` and `ncols` after their [got set in `dbm_create`](https://github.com/cp2k/cp2k/blob/master/src/dbm/dbm_matrix.c#L40-L41). For this one could use the routines `dbm_get_row_block_sizes` and `dbm_get_col_block_sizes` from [dbm_api.F](https://github.com/cp2k/cp2k/blob/master/src/dbm/dbm_api.F).

**Comment by mkrack** [comment]
@oschuett Thanks for looking into the report and for the hints. I am afraid that we will still have to deal for the time being with the classic Intel Fortran compiler `ifort`, because CP2K cannot be compiled currently with the new Fortran compiler `ifx` due to catastrophic compiler errors.

**Comment by oschuett** [comment]
The problem is indeed related to the ISO_C_BINDINGS, more specifically the `bool` arguments. The old `ifort` encodes `.TRUE.` as `-1`, while the standard actually mandates it to be encoded as `1`.  The new `ifx` then goes on and relies on the standard encoding when it compiles [these ternary operators](https://github.com/cp2k/cp2k/blob/0165da4645489888fae55c9cbb9ccbdcebf313e1/src/dbm/dbm_multiply.c#L306-L309) using "math" instead of jumps. 

The fix is to supply [`-fpscomp logicals`](https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2023-0/fpscomp.html). I also tried [`-standard-semantics`](https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2023-0/standard-semantics.html), which includes the former flag, but it led to linker errors. See also [this discussion](https://community.intel.com/t5/Intel-Fortran-Compiler/ifort-might-return-an-incorrect-C-BOOL-true-in-iso-c-binding/m-p/999050).

**Comment by oschuett** [comment]
Btw, I had to remove the `-xHost` flag to use `ifx` on my AMD Threadripper machine because otherwise the resulting binaries would bail out with:

```
Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, MOVBE, POPCNT, AVX, F16C, FMA, BMI, LZCNT, AVX2 and ADX instructions.
```

**Comment by mkrack** [comment]
@oschuett thanks for looking at this and solving it. It's a bit concerning that the compiler's default behavior is non-standard.
