### ISSUE TITLE
How to initialize the mpi_comm for the CP2K library

### ISSUE THREAD

**Issue by Pibemanden** [cp2k/cp2k#2720]
After the MPI library has been updated I am wondering how to call the subroutine to initialize the force environments:

```
RECURSIVE SUBROUTINE create_force_env(new_env_id, input_declaration, input_path, &
                                         output_path, mpi_comm, output_unit, owns_out_unit, &
                                         input, ierr, work_dir, initial_variables)
```

The mpi_comm parameter used to be a 'INTEGER' type, and here I called with the corresponding old style mpi_comm handle, but I guess that now I will have to construct an mp_comm_type which is an internal type in CP2K.

So my question is how to go from the mpi_comm integer handle to an mp_comm_type, so that I can call the create_force_env correctly?

**Comment by fstein93** [comment]
I order to obtain an mp_comm_type from an integer handle is to declare your new object mpi_comm of type mp_comm_type and use `CALL <your_new_communicator>%set_handle(<your_integer_handle>)`. If you need the integer handle of a given communicator, use `<integer_handle> = <communicator>%get_handle()`

The reason for these new types is that the new mpi_f08 module introduces its own MPI types such as MPI_Comm representing a communicator. Because CP2K is also supposed to be compiled with the old mpi module or even without MPI support, I have to wrap the MPI types. This also allows us to apply the OOP features from Fortran as communication routines always require a communicator anyways.

**Comment by fstein93** [comment]
What are you trying to achieve?

**Comment by Pibemanden** [comment]
Thank you for your reply. I am just trying to update our interface code for CP2K to also work with the new versions of CP2K with the improved MPI interface.

How our program works is that we separate the MPI world communicator into N sub communicators which each do their own  electronic structure calculation to get energies, gradients and stress tensors.

**Comment by fstein93** [comment]
Have you already considered [CP2K's farming capabilities](https://manual.cp2k.org/trunk/CP2K_INPUT/FARMING.html)?

**Comment by Pibemanden** [comment]
That seems very neat. We are running path integral molecular dynamics though, so our use-case is more geared towards using the interface and restarting the calculations using the previous electronic structure as a starting point for the individual beads in the calculation. Thank you for your suggestion.

**Comment by fstein93** [comment]
Apparently, the issue is solved. Feel free to reopen it if necessary.
