### ISSUE TITLE
Project file is out of date

### ISSUE THREAD

**Issue by lucy114514** [cp2k/cp2k#2727]
I want to do an exercise for Adsorption of acetylene on an intermetallic surface from exercise 2018 lecture 6, but the tar file is out of date, and my own modeling always have some problem, could someone please provide me with this file,I will be very grateful.That site is https://www.cp2k.org/exercises:2018_ethz_mmm:adsorption_2018

**Comment by oschuett** [comment]
Unfortunately, the old exercises are not being maintained because they were created for specific lectures. For that particular exercise you could try to contact the last author of the linked paper: https://dx.doi.org/10.1021%2Fja505936b

More generally, we're working on a curated collection of common exercises that will be kept up-to-date:
https://www.cp2k.org/exercises:common:index

I'm going to close this issue now because it's actually more of user question. In the future please post those to our [forum](https://www.cp2k.org/howto:forum).
