### ISSUE TITLE
ELPA conftest.F90(3): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MKL_SERVICE]

### ISSUE THREAD

**Issue by LM99v** [cp2k/cp2k#3158]
Dear all,

I use Intel OneAPI 2021.5 to compile cp2k 2023.2, and I have one trouble on installing EPLA-2022.11.001 which shows an error in opening the compiled module file.  Check INCLUDE paths.   [MKL_SERVICE].

configure:10085: /share/data2/apps/intel2022/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort -c -O2 -fPIC -fp-model=precise -funroll-loops -g -qopenmp -qopenmp-simd -traceback -xHost  conftest.F90 >&5
configure:10085: $? = 0
configure:10093: result: no
configure:10221: checking for fc option to support OpenMP
configure:10237: /share/data2/apps/intel2022/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort -o conftest -O2 -fPIC -fp-model=precise -funroll-loops -g -qopenmp -qopenmp-simd -traceback -xHost   conftest.F90 -lmpifort -lmpi  >&5
configure:10237: $? = 0
configure:10270: result: none needed
configure:10291: checking whether mpi-launcher should be detected automatically
configure:10301: result: yes
configure:10304: checking whether a specific MPI launcher should be used
configure:10336: result: no
configure:10351: checking for mpiexec.hydra
configure:10372: found /share/data2/apps/intel2022/oneapi/mpi/2021.5.1//bin/mpiexec.hydra
configure:10383: result: mpiexec.hydra
configure:10401: checking whether stdout/stderr file redirect should be enabled
configure:10417: result: no
configure:10420: checking whether ELPA library should contain also single precision functions
configure:10430: result: no
configure:10703: checking whether Fortran module iso_fortran_env is available
configure:10715: /share/data2/apps/intel2022/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort -c  -O2 -fPIC -fp-model=precise -funroll-loops -g -qopenmp -qopenmp-simd -traceback -xHost   conftest.F90 >&5
configure:10715: $? = 0
configure:10723: result: yes
configure:10732: checking whether we can compile a Fortran program using MKL
configure:10744: /share/data2/apps/intel2022/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort -c  -O2 -fPIC -fp-model=precise -funroll-loops -g -qopenmp -qopenmp-simd -traceback -xHost   conftest.F90 >&5
conftest.F90(3): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MKL_SERVICE]

[config.log](https://github.com/cp2k/cp2k/files/13645584/config.log)

Here is the config.log file from build-cpu folder. Thank you for help.

**Comment by Anyborr** [comment]
I'm not an expert on compiling cp2k, but in your config (line 520) you get the message 
`configure:8162: WARNING: Your processor and OS supports ABM instructions but not your compiler, can you try another compiler?`

It looks like you're using GCC version 8.4.0 which is quite old. Maybe try with the toolchain flag `--with-gcc=install` and see if that helps?

**Comment by LM99v** [comment]
@Anyborr Our HPC GPU node runs cuda-10.1 and it cannot support gcc higher than 8. Besides, the OS is CentOS 7.

**Comment by fstein93** [comment]
Alternatively, you may try to compile CP2K without ELPA support by setting `--with-elpa=no`. If your HPC center has ELPA installed, use `--with-elpa=system` or `--with-elpa=/your/path/to/elpa` instead.
If you actually need ELPA, you may check whether there is a way to install ELPA using a center provided service (Spack?). In general, I am also not sure about the compatibility of your ELPA version with the latest CP2K release and your available compilers. For more information on the compiler support of CP2K, check [here](https://www.cp2k.org/dev:compiler_support). The oldest compiler we test with ELPA (see [here](https://dashboard.cp2k.org/index.html)), is GCC9.3 on GPU (CUDA 12, ELPA 2023), so it might be that our build system does not support your platform anymore. From your config file, I cannot tell what the issue is. Maybe, you can ask the ELPA developers as it seems to be ELPA-related. If you build ELPA with the toolchain, check [this file](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/stage5/install_elpa.sh) for more information on the build process.

**Comment by fstein93** [comment]
Apparently, the issue was resolved. If you need more assistance with your issue, feel free to reopen it.
