### ISSUE TITLE
Inconsistencies in Energy Using OUTERSCF in CP2K and Using OT, DIAGNOSE Algorithms

### ISSUE THREAD

**Issue by Miller10101010** [cp2k/cp2k#3197]
In CP2K, when using the OT (Optimization of the Time-Dependent Density Functional Theory) algorithm and the Diagnose algorithm, and performing single-point energy calculations with and without OUTERSCF, the energy differences are respectively 1 hartree and 1E-5 hartree. Are the results reliable?
We calculate the single-point energy of 128 water molecules. Here are input file.
Thanks!!
H2O_400.inp：OT-NO OUTSCF
H2O_outSCF.inp：OT-USE OUTSCF
H2O_diag.inp：OT-DIAGNOSE
[OUTSCF.zip](https://github.com/cp2k/cp2k/files/13818429/OUTSCF.zip)

**Comment by fstein93** [comment]
I have just checked your input files. Apparently, you mean diagonalization. Is it intentional that you employ no purification method in the AUXILIARY_DENSITY_MATRIX_METHOD section in H2O_diag.inp compared to the MO_DIAG scheme in the other two calculations? Purification changes the density matrix and as such will affect the results of your calculations.
An energy difference of 1E-5 hartree or ca. 1E-7 hartree per molecule should be accurate enough for many purposes.

**Comment by Miller10101010** [comment]
Thank you very much for responding to my question! If I change the "NONE" setting to "MO-DIAG" in the diagonalization method, it prompts an error message (ADMM: MO-based purification requires OT.). So, I modified the input file for the OT algorithm to "NONE" and compared it with diagonalization, finding a difference of about 1E-4 Hartree.

Some people mention that under normal circumstances, the energy after OT convergence should be exactly the same as that obtained from diagonalization (within the convergence limit). If the energy from OT is significantly higher than that from diagonalization, it might be that OT coincidentally converged to an unstable wave function, in which case the results from OT should not be used. Additionally, if purification is not performed, the ADMM part may also cause a decrease in accuracy for diagonalization.

Finally, including "OUTSCF" significantly improves convergence speed. Considering both energy accuracy and speed, if I were to analyze the reaction barrier subsequently, which method would you recommend for single-point energy calculations: diagonalization method ("NONE"), OT algorithm ("MO-DIAG"), OT algorithm ("NONE"), OT algorithm ("NONE&outSCF"), or OT algorithm ("MO-DIAG&outSCF")?
Thanks!

**Comment by fstein93** [comment]
Convergence tends to be better with diagonalization (less approximations, somewhat a direct approach), but performance can be poor due to the high prefactor of the required full eigenvalue decomposition. If performance (run time) is an issue or you want to ensure a physically more meaningful density matrix within the ADMM approximation, switch to OT. OUTER_SCF improves the convergence properties due to updated preconditioners which will be of interest for you if you analyze reaction barriers. If you are not sure whether you need purification, do some tests. I personally never used it because certain features I need (second order gradients) are not implemented in my case.

**Comment by Miller10101010** [comment]
thanks！！
