### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Darkasleif** [cp2k/cp2k#3287]

**Comment by fstein93** [comment]
Sorry for the late reply. Your log file is incomplete. There is no error message given.
Why do you want to use CP2K on a Windows machine with CUDA (presumably a Desktop/Notebook with a consumer GPU)? We do not recommend it because CP2K relies mostly on double-precision operations which are not much (if at all) faster on consumer GPUs than on CPUs. Here, it is better to stay with the latter or switch to a cluster with more performant GPUs (if available).
