### ISSUE TITLE
PW_DFT/SETTINGS section

### ISSUE THREAD

**Issue by hmhoseini** [cp2k/cp2k#3470]
It seems that some keywords of this section is not known for CP2K (CP2K version 2024.1 (Development Version)). Here is an example of "ITSOL_TOL_MIN" 
![Screenshot from 2024-06-13 10-24-31](https://github.com/cp2k/cp2k/assets/81620104/8fd7383a-e2db-4b33-a1cb-52ae82143199)

**Comment by oschuett** [comment]
The keywords in the `PW_DFT` section are provided by SIRIUS. The latest version has [ITSOL_TOL_MIN](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/PW_DFT/SETTINGS.html#CP2K_INPUT.FORCE_EVAL.PW_DFT.SETTINGS.ITSOL_TOL_MIN).

Presumably you are using an old version of SIRIUS.

**Comment by toxa81** [comment]
The tagged version should be working, correct? We will have a look at the development version. Indeed, some input items were reshuffled.

**Comment by toxa81** [comment]
@hmhoseini you might be using an outdated version of input file. Can you please post it here for inspection by @mtaillefumier ?

**Comment by hmhoseini** [comment]
@toxa81 
@mtaillefumier 
I don think so. Some keywords cause no problem.
SIRIUS version: SIRIUS 7.5.3, git hash: f184b8131e642bdb0fa204fe17bbe404d8fc82d0

[issue.zip](https://github.com/user-attachments/files/15821175/issue.zip)
[issue.zip](https://github.com/user-attachments/files/15821175/issue.zip)

**Comment by mtaillefumier** [comment]
The option exists when cp2k is compiled with sirius 7.5.2 but is not present with sirius develop. The commit in SIRIUS changing this is 8d239f6a671ced70f73b60605f443325eebe0614.

If you use sirius develop (7.5.3), you have to use `MIN_TOLERANCE` instead of `ITSOL_TOL_MIN` and put it in the `iterative_solver` section of the input file. 

CP2K documentation is not synchronized with SIRIUS develop .
