### ISSUE TITLE
AIMD Supercell Size for Perfect Crystals.

### ISSUE THREAD

**Issue by hongyi-zhao** [cp2k/cp2k#3569]
Hello **cp2k** community,

I'm planning to run some Ab Initio Molecular Dynamics (AIMD) simulations on perfect crystal systems. I have a question regarding the use of supercells: **Is it always necessary to use an appropriately sized supercell for AIMD simulations, even when dealing with perfect crystals?**

I understand that supercells are crucial for studying defects and can help with issues like phonon sampling and finite size effects. However, I'm unsure if these considerations are as important for a perfect crystal structure. Specifically, I'd appreciate insights on:

1. The main advantages of using a supercell for perfect crystals in AIMD.
2. Potential drawbacks or inaccuracies that might arise from using a smaller cell.
3. Guidelines for determining an appropriate supercell size for AIMD of perfect crystals.
4. Any computational tricks or settings in **cp2k** that could help balance accuracy and efficiency when choosing supercell size.

Thank you in advance for your expertise and advice!

Regards,
Zhao

**Comment by fstein93** [comment]
Dear @hongyi-zhao ,
Please excuse the long time of an answer. This question would have been better suited for the Google user group. The Github issues are meant to discuss specific technical/code-related issues.
To answer your questions:
1. In case of highly symmetric systems k-point approaches are advantageous because the symmetries reduce the number of k-points which is not possible in super cells. In case of asymmetric systems (triclinic cells or simulations/MD/MC/...), super cell approaches are advantageous because they do not require complex arithmetics.
2. Super cell approaches of crystals are equivalent to k-point approaches, i.e. a 2x2x2 super cell is equivalent to a 2x2x2 k-point mesh. Too small super cells/ k-point meshes cannot describe finite size effects properly. In case of HF, the Coulomb potential needs a truncation according to the distance to the nearest-neighbor. If the cell is too small, this introduces additional errors.
3. You have to test for your system of interest. But from experience, you will observe reasonable energies if the super cell has a size of at least (10 A)^3.
4. The computational setup is the similar to systems within the unit cell. Converge the parameters CUTOFF, REL_CUTOFF, EPS_DEFAULT and the parameters required by your method of choice.
