### ISSUE TITLE
Tester with GCC14

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#3614]
I would be great to have a tester run with GCC14. I am currently testing the latest toolchain with GCC14. GCC14 finds more bugs than GCC13 which I am currently fixing. Especially, there are issues with OpenMPI.

**Comment by oschuett** [comment]
Our OpenMPI tester actually [doubles](https://github.com/cp2k/cp2k/blob/aeb36dafce61d0049299805e3fd9add5799983e0/tools/docker/generate_dockerfiles.py#L30) as tester for the latest GCC (currently 14.1.0). Since sometimes we have trouble with both packages, that setup is probably not ideal. I'll add a separate tester just for the latest GCC.

**Comment by fstein93** [comment]
Short update:
GCC14 compiles the toolchain+OpenMPI and CP2K in serial mode (after some fixes). In parallel mode, there are linking errors with Scalapack.
With GCC13, everything seems fine except from grid_unittest failing with FE_DIVBYZERO.
With GCC14, I have similar linking errors with MPICH. I compiled unter WSL2 (default settings).

**Comment by mkrack** [comment]
The PSI/Merlin tester for [MPICH 4.0.3](https://dashboard.cp2k.org/archive/psi-gnu-mpich-psmp/index.html) and [OpenMPI 5.0.5](https://dashboard.cp2k.org/archive/psi-gnu-openmpi-psmp/index.html) are using the GCC 14.1.0 compiler already for quite a while. The same is true for the [macOS Apple M1](https://dashboard.cp2k.org/archive/darwin-gnu-arm64-psmp/index.html) tester. So, there already 3 tester running and clean (including release v2024.2) for GCC14. Nevertheless a separate GCC14 tester makes sense.
