### ISSUE TITLE
Wrong results when calculating O2 G0W0+BSE

### ISSUE THREAD

**Issue by Fisherd99** [cp2k/cp2k#3620]
When I calculate O2 BSE, I get wrong results of GW energy
```
  ------------
  G0W0 results
  ------------
   
  Molecular orbital   E_SCF (eV)       Sigc (eV)   Sigx-vxc (eV)       E_GW (eV)
     1 ( occ )         -514.0880       -240.0537        -48.8975       -803.0392
     2 ( occ )         -514.0854       -345.7599        -48.8707       -908.7160
     3 ( occ )          -32.4549         27.7777        -12.3357        -17.0129
     4 ( occ )          -19.4875         18.6111        -10.1012        -10.9777
     5 ( occ )          -12.9881          8.8957         -6.7905        -10.8829
     6 ( occ )          -12.6373         10.7810         -9.1224        -10.9787
     7 ( occ )          -12.6373          5.4992         -3.8400        -10.9781
     8 ( occ )           -5.5354      29621.1369         -7.9366      29607.6648
     9 ( vir )           -5.5354     -29998.5725          8.0221         -5.5354
    10 ( vir )            4.4039        -12.3080          7.8109          4.4039
```
In this calculation, I use cc-pVTZ and cc-pVTZ-RIFIT, which is downloaded from Basis Set Exchange https://www.basissetexchange.org/basis/cc-pvtz-rifit/format/cp2k/?version=1&elements=8 . And I find this wrong results will also occur with other Duning's basis set.

[O2-BSE.zip](https://github.com/user-attachments/files/16569218/O2-BSE.zip)

**Comment by MGraml** [comment]
Hi @Fisherd99,

since you want to compute O2, you need to perform an open shell calculation (Keywords [UKS](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT.html#CP2K_INPUT.FORCE_EVAL.DFT.UKS) T and [Multiplicity](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT.html#CP2K_INPUT.FORCE_EVAL.DFT.MULTIPLICITY) 3). 
Open shell calculations are not yet implemented for the BSE module, but for G0W0 this fixes the diverging energies. 
I executed your example with a slightly cleaned version: If you use UKS and Multiplicity 3, there is no need for special SCF parameters. I also removed the print statements as well as the ADMM stuff (since PBE is applied) and reduced the cell size a bit.

[O2-G0W0.zip](https://github.com/user-attachments/files/16597733/O2-G0W0.zip)

Edit: I attach the G0W0 results directly:


        ------------
        G0W0 results
        ------------
        
        ---------------------------------------
        GW quasiparticle energies of alpha spins
        ----------------------------------------
         
        Molecular orbital   E_SCF (eV)       Sigc (eV)   Sigx-vxc (eV)       E_GW (eV)
           1 ( occ )         -514.2508         -1.3983        -49.1859       -564.8350
           2 ( occ )         -514.2482         -1.5249        -49.1691       -564.9423
           3 ( occ )          -32.9092          6.0781        -13.2971        -40.1282
           4 ( occ )          -20.2409          3.9901        -11.8690        -28.1197
           5 ( occ )          -13.4244          2.3961         -8.9961        -20.0245
           6 ( occ )          -13.4244          2.3961         -8.9961        -20.0245
           7 ( occ )          -13.3455          1.0024         -7.2610        -19.6041
           8 ( occ )           -6.5287          2.8329         -7.7689        -11.4647
           9 ( occ )           -6.5287          2.8329         -7.7689        -11.4647
          10 ( vir )            4.0194         -2.4512          7.4529          9.0211
          11 ( vir )           12.4530         -2.8229          7.1985         16.8287
          12 ( vir )           12.6976         -1.4167          5.9882         17.2692
          13 ( vir )           12.6976         -1.4167          5.9882         17.2692
          14 ( vir )           14.1346         -2.1168          5.7839         17.8018
          15 ( vir )           15.8860         -2.1655          5.8650         19.5855
          16 ( vir )           15.8860         -2.1655          5.8650         19.5855
          17 ( vir )           16.7643         -2.5879          7.1199         21.2963
          18 ( vir )           31.1314         -2.0648          8.1751         37.2417
          19 ( vir )           31.1314         -2.0648          8.1751         37.2416
         
        Alpha GW HOMO-LUMO gap (eV)                                            20.4858
        
        ------------------------------------------------------------------------------
        
        
        ---------------------------------------
        GW quasiparticle energies of beta spins
        ---------------------------------------
         
        Molecular orbital   E_SCF (eV)       Sigc (eV)   Sigx-vxc (eV)       E_GW (eV)
           1 ( occ )         -513.5422         -0.6682        -48.6386       -562.8490
           2 ( occ )         -513.5396         -0.1335        -48.6026       -562.2757
           3 ( occ )          -31.7319          3.1872        -11.4793        -40.0240
           4 ( occ )          -18.4502          5.5619         -8.4972        -21.3855
           5 ( occ )          -12.4250          1.4079         -6.3566        -17.3736
           6 ( occ )          -11.5573         -0.6425         -4.2295        -16.4292
           7 ( occ )          -11.5573         -0.6425         -4.2295        -16.4292
           8 ( vir )           -4.1984         -2.4562          7.4638          0.8092
           9 ( vir )           -4.1984         -2.4562          7.4638          0.8092
          10 ( vir )            4.9915         -3.0435          8.0530         10.0011
          11 ( vir )           12.9721         -2.2560          7.5604         18.2765
          12 ( vir )           13.6077         -1.7850          6.7476         18.5703
          13 ( vir )           13.6077         -1.7850          6.7476         18.5703
          14 ( vir )           14.4767         -1.3009          5.7865         18.9623
          15 ( vir )           16.9353         -2.6213          6.8556         21.1696
          16 ( vir )           16.9353         -2.6213          6.8556         21.1696
          17 ( vir )           17.4906         -2.1492          7.1217         22.4631
          18 ( vir )           32.3531         -1.7115          8.5513         39.1929
          19 ( vir )           32.3531         -1.7115          8.5513         39.1929
         
        Beta GW HOMO-LUMO gap (eV)                                             17.2384


I hope this helps. Have a nice summer!
Max

**Comment by Fisherd99** [comment]
Thanks @MGraml. I find it also works when I just delete `SMEAR` section without open spin shell and add `EPS_SCF 0.14` to let scf roughly converge. Of course, in terms of physics, it is right to use UKS and Multiplicity 3 for O2 rather than close spin shell calculation.

Notice in original calculation there is occupation-1 in degenerative MO 8 and 9
```
 MO|      6              -0.464412             -12.637294               2.000000
 MO|      7              -0.464412             -12.637294               2.000000
 MO|      8              -0.203422              -5.535395               1.000000
 MO|      9              -0.203422              -5.535395               1.000000
 MO|     10               0.161842               4.403939               0.000000
```
and in non-smear calculation the result is
```
 MO|      6              -0.473664             -12.889052               2.000000
 MO|      7              -0.461423             -12.555967               2.000000
 MO|      8              -0.203332              -5.532953               2.000000
 MO|      9              -0.194425              -5.290585               0.000000
 MO|     10               0.163168               4.440039               0.000000
```
I wonder whether this problem is caused by fractional occupation in original calculation?

Also, I find it reports `CPASSERT failed` when I use `ADDED_MOS -1` in open shell calculation, but works well when I use `ADDED_MOS 1000` to cover full set of unoccupied MOs.

By the way, it seems that BSE task can finish with open spin shell. I don't understand what you mean "Open shell calculations are not yet implemented for the BSE module".

**Comment by MGraml** [comment]
Hello,

thank you for your email. 
I am out of office until September 1st.

I will get back to you then.

Best regards,
Max Graml

>>> Ziqing Guan ***@***.***> 23.8.24 22:14 >>>

Thanks. I find it also works when I just delete `SMEAR` section without open spin shell and add `EPS_SCF 0.14` to let scf roughly converge. Of course, in terms of physics, it is right to use UKS and Multiplicity 3 for O2 rather than close spin shell calculation.

Notice in original calculation there is occupation-1 in degenerative MO 8 and 9
```
 MO|      6              -0.464412             -12.637294               2.000000
 MO|      7              -0.464412             -12.637294               2.000000
 MO|      8              -0.203422              -5.535395               1.000000
 MO|      9              -0.203422              -5.535395               1.000000
 MO|     10               0.161842               4.403939               0.000000
```
and in non-smear calculation the result is
```
 MO|      6              -0.473664             -12.889052               2.000000
 MO|      7              -0.461423             -12.555967               2.000000
 MO|      8              -0.203332              -5.532953               2.000000
 MO|      9              -0.194425              -5.290585               0.000000
 MO|     10               0.163168               4.440039               0.000000
```
I wonder whether this problem is caused by fractional occupation in original calculation?

By the way, it seems that BSE task can finish with open spin shell. I don't understand what you mean "Open shell calculations are not yet implemented for the BSE module".

**Comment by MGraml** [comment]
Hi @Fisherd99,

1. I would rather stay with `UKS TRUE`. I am not sure how reliable the SCF with such a large `EPS_SCF` is.
2. Yes, either setting a large integer or specifying alpha and beta by `ADDED_MOS -1 -1` should work.
3. Maybe you did not invoke `UKS TRUE` in your cp2k runs with BSE? If I change the example from my first reply slightly by additionally introducing the BSE-section, the calculation aborts in the RI-RPA section (as it should, since there is no tested implementation of open shell systems for BSE in cp2k until now) with

       *******************************************************************************
       *   ___                                                                       *
       *  /   \                                                                      *
       * [ABORT]                                                                     *
       *  \___/             BSE not implemented for open shell calculations          *
       *    |                                                                        *
       *  O/|                                                                        *
       * /| |                                                                        *
       * / \                                                           mp2_gpw.F:353 *
       *******************************************************************************

Best,
Max

**Comment by Fisherd99** [comment]
Thanks for your reply @MGraml ,
 1. I'm sure I've invoked `UKS T` in my calculation. The input and result file are attached here: 
[O2-BSE_with_UKS.zip](https://github.com/user-attachments/files/16880712/O2-BSE_with_UKS.zip)

 2. Another question: If I want to use `TZVP-MOLOPT-GTH` `TZV2P-MOLOPT-GTH` `TZV2PX-MOLOPT-GTH` basis set in file `BASIS_MOLOPT` to calculate GW and BSE, which RI_AUX basis set should I assign? 
 I see some relevant content in file `BASIS_RI_MOLOPT`, but I can't understand what the meaning of RI basis name is, like what `O  RI_84_6_6_5_5_0_0_0_2.4e-07` stands for. So I can't decide which one should I choose.

==== added for second edit ======

Oh I see, the RI_AUX name means it has 6\*1+6\*3+5\*5+5\*7=84 basis. Am I right ? But I'm still confused with "relative accuracy of RI-MP2: 2.4e-07".

 3. What's the difference between AUX_FIT and RI_AUX? I tried to set `RI_AUX admm-dzp-q6` but got wrong result.

**Comment by MGraml** [comment]
Hi @Fisherd99,

1. From your example it seems, that you ran cp2k on commit `96bff0e` from late July. The change to catch Open-Shell calculations before BSE has been made in PR(#3597). I suppose pulling and rebuilding cp2k should fix that issue.
2. As of now, I would recommend to use the `aug-cc-pVXZ` basis set family instead. Smaller tests suggested poor convergence of the BSE results for your proposed basis sets. We are currently working on `MOLOPT-GTH` basis sets suitable for GW/GW+BSE.
Regarding the nomenclature: The relative error refers to the error introduced by applying RI using these basis sets relative to non-RI mp2. 
4. You should set `AUX_FIT` when applying a hybrid functional and the ADMM. Since you use `PBE` as xc-functional, there is no need for ADMM or `AUX_FIT`. You can find more details [here](https://www.cp2k.org/exercises:2017_uzh_cp2k-tutorial:hybrid#auxiliary_density_matrix_methods_admm). `RI_AUX` is the keyword you should use to specify the RI-basis, e.g. `def2-TZVP-RIFIT` or `aug-cc-pVTZ-RIFIT` etc., depending on your `BASIS_SET ORB`. Here, I would recommend to use the basis sets `aug-cc-pVXZ-RIFIT` together with the above mentioned `aug-cc-pVXZ`.

Does that solve the original issue about the diverging results for GW/BSE?

Best,
Max

**Comment by Fisherd99** [comment]
Thanks for your answer @MGraml .

For point 1, I update to v2024.2 `commit 6608d10` and get the same result "BSE not implemented for open shell calculations" as you said.

That's all my questions. Hope `MOLOPT-GTH` suitable for GW/GW+BSE will come soon.
