### ISSUE TITLE
How to incorporate the FLO-SIC into PBE functional in the CP2K？

### ISSUE THREAD

**Issue by Yvvq0217** [cp2k/cp2k#3653]
I hope incorporate the Fermi-Lowdin orbital self-interaction correction (FLO-SIC) method into PBE functional in the CP2K program. But I only saw relevant papers that did not include implementation methods. 
Some paper about that:  https://doi.org/10.1002/jcc.25586;  https://doi.org/10.1002/jcc.26168; 10.1088/1361-648X/abc407

**Comment by juerghutter** [comment]
Hi

there are several other SIC methods implemented. In order to add this new method, I would follow the
previous implementations. As this is non-trivial (but also not too hard) I would suggest to team up with
an experienced CP2K developer.

regards
JH

________________________________________
From: Yvvq0217 ***@***.***>
Sent: Tuesday, September 3, 2024 1:06 PM
To: cp2k/cp2k
Cc: Subscribed
Subject: [cp2k/cp2k] How to incorporate the FLO-SIC into PBE functional in the CP2K？ (Issue #3653)

I hope incorporate the Fermi-Lowdin orbital self-interaction correction (FLO-SIC) method into PBE functional in the CP2K program. But I only saw relevant papers that did not include implementation methods.
Some paper about that: https://doi.org/10.1002/jcc.25586; https://doi.org/10.1002/jcc.26168; 10.1088/1361-648X/abc407

―

**Comment by Yvvq0217** [comment]
Alright. Thanks so much!



---- Replied Message ----
| From | Juerg ***@***.***> |
| Date | 09/06/2024 15:45 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [cp2k/cp2k] How to incorporate the FLO-SIC into PBE functional in the CP2K？ (Issue #3653) |

Hi

there are several other SIC methods implemented. In order to add this new method, I would follow the
previous implementations. As this is non-trivial (but also not too hard) I would suggest to team up with
an experienced CP2K developer.

regards
JH

________________________________________
From: Yvvq0217 ***@***.***>
Sent: Tuesday, September 3, 2024 1:06 PM
To: cp2k/cp2k
Cc: Subscribed
Subject: [cp2k/cp2k] How to incorporate the FLO-SIC into PBE functional in the CP2K？ (Issue #3653)

I hope incorporate the Fermi-Lowdin orbital self-interaction correction (FLO-SIC) method into PBE functional in the CP2K program. But I only saw relevant papers that did not include implementation methods.
Some paper about that: https://doi.org/10.1002/jcc.25586; https://doi.org/10.1002/jcc.26168; 10.1088/1361-648X/abc407

―
