### ISSUE TITLE
SIRIUS ignores CP2K output file

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#371]
When redirecting the CP2K output via `-o other.out` is the SIRIUS output still directed towards stdout.

Unfortunately this seems to be still completely compiler specific: https://gcc.gnu.org/onlinedocs/gfortran/FNUM.html

... so I guess we should at least document this somewhere.

**Comment by mtaillefumier** [comment]
SIRIUS output can be shut down almost completely if needed (the VERBOSE option). But there is no simple way to redirect the output of SIRIUS in the same file that contains the output of cp2k without doing hacky things in both codes. 

Moreover, I am reluctant to introduce something that is compiler dependent. Giving the name of the output file won't work either because the file will be rewritten by either cp2k or SIRIUS.

**Comment by oschuett** [comment]
Ideally, SIRIUS would take callback for logging. Then we could nicely integrate it with the CP2K [printkeys](https://www.cp2k.org/dev:printkey).

**Comment by dev-zero** [comment]
That's likely the only way to integrate it since sharing filedescriptors is not an option.

**Comment by oschuett** [comment]
I don't think there any plans for SIRIUS to integrate with CP2K printkeys. For now the problem has been mitigated via #1680.
