### ISSUE TITLE
too many communicators

### ISSUE THREAD

**Issue by recohen** [cp2k/cp2k#546]
I am getting the following crashes reproducibly after several thousand time steps:

 *******************************************************************************
 *             MPI error 672742415 in mpi_cart_sub @ mp_cart_sub : Other MPI   *
 *   ___         error, error stack:
PMPI_Cart_sub(228)..................:     *
 *  /   \        MPI_Cart_sub(comm=0xc4040010, remain_dims=0x7f200ce27e80,     *
 * [ABORT]                       comm_new=0x2b5549318b64)                      *
 *  \___/              failed
PMPI_Cart_sub(167)..................:            *
 *    |                  
MPIR_Comm_split_impl(253)...........:               *
 *  O/|       
MPIR_Get_contextid_sparse_group(604): Too many communicators   *
 * /| |                 (0/32768 free on this process; ignore_id=0)            *
 * / \                                                    dbcsr_mpiwrap.F:1098 *
 *******************************************************************************

 ===== Routine Calling Stack =====

           14 mp_cart_sub
           13 dbcsr_complete_redistribute
           12 copy_dbcsr_to_fm
           11 cp_dbcsr_sm_fm_multiply
           10 make_basis_sm
            9 reorthogonalize_vectors
            8 wfi_extrapolate
            7 scf_env_initial_rho_setup
            6 init_scf_run
            5 qs_energies
            4 qs_forces
            3 velocity_verlet
            2 qs_mol_dyn_low
            1 CP2K

It seems that there is a communicator leak--more communicators are created than destroyed. This is using the latest code for github . I am using 2019 intel compilers and mkl ,
but it seems to be a problem in cp2k dbscr. I am running psmp hybrid with 384 cores and OMP_NUM_THREADS=4 . I am stuck until I can get pas this.

Thanks!

Ron

**Comment by alazzaro** [comment]
I don't know if this is relevant, but I've recently introduced a check into DBCSR for the number of created communicators (note that a similar test is also in CP2K). Basically, the number sub-communicators at the end of the DBCSR execution must be zero:

https://github.com/cp2k/dbcsr/blob/9041c952677d5cec4f888fc62738e09de812c0b3/src/core/dbcsr_lib.F#L321

I was not able to find any communicator leak in the CP2K tests...

Could you share your CP2K input? I can give a try... How long takes to reach the limit?
BTW, you don't mention which MPI implementation you are using.
Otherwise, you can add some debugging and print the number of created communicators. Add print for the number of created communicators `debug_comm_count` before the line

https://github.com/cp2k/dbcsr/blob/9041c952677d5cec4f888fc62738e09de812c0b3/src/mpi/dbcsr_mpiwrap.F#L1304

In this way, you can see how many sub-communicators are created before the crash.

For a more invasive debugging, you can add a print just after *every* change of the variable `debug_comm_count` (no so many), so yo can see how this value grows.

I found that the limit for Intel MPI is 16381 (see https://software.intel.com/en-us/forums/intel-clusters-and-hpc-technology/topic/279324)
