### ISSUE TITLE
Verify recent versions of spglib with CP2K

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#562]
Current master of CP2K has the following check:

https://github.com/cp2k/cp2k/blob/5566d17405ab6f351561817a83675b3344ac2a5a/src/cryssym.F#L168-L170

with spglib-1.9.9 being released in 2016 and the toolchain shipping 1.12.2.

Counterintuitively I get this warning even with `FORCE_EVAL/DFT/KPOINTS/SYMMETRY` set to `.FALSE.`

Do we have a test set for spglib-based functionality?

**Comment by oschuett** [comment]
We depend on spglib in two ways: Directly via `cryssym.F` and indirectly through SIRIUS.

The problem with such a situation is that a version upgrade requires a concerted effort by otherwise independent developer(-teams). In this case we got lucky because so far the API seems to be backwards compatible, or we simply didn't notice because we're using our own [Fortran bindings](https://github.com/cp2k/cp2k/blob/master/src/spglib_f08.F). Nevertheless, we do have some [test coverage](https://www.cp2k.org/static/coverage/src/cryssym.F.gcov.html) and those tests are passing.

Generally, I expect to see more of such problems as the trend towards libraries continues.
Welcome to [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell) ;-)
