### ISSUE TITLE
Error during linking with libint with "-align array64byte" option in FCFLAGS.

### ISSUE THREAD

**Issue by jjlow** [cp2k/cp2k#7]
I noticed errors similar to the following during linking of the Intel branch of cp2k with the Intel compilers (17.0.4 20170408), MKL and Intel-MPI on a Broadwell cluster.

Warning: alignment 32 of symbol `build_eri' in /home/jlow/cp2k-2017/170622/libint/lib/libint.a(init_libint.o) is smaller than 64 in /home/jlow/cp2k-2017/170622/cp2k/lib/Linux-x86-64-intel-bdw-mod/psmp/libcp2kmain.a(hfx_libint_wrapper.o)

I found that I needed to remove the "-align array64byte" option in Linux-x86-64-intel.x to build cp2k without warnings (and only eight errors during registry testing).

Does removing the "-align array64byte" hurt performance on KNL?  Is there a workaround to this issue?

I have attached an archive containing the arch files I used in my build.

Thanks,

John J. Low, Argonne National Laboratory.

[Archive.zip](https://github.com/cp2k/cp2k/files/1165821/Archive.zip)

**Comment by oschuett** [comment]
Hi John,

thanks for your report. Maybe @hfp could comment?

-Ole

**Comment by alazzaro** [comment]
I'm going to close this issue. Please reopen it if you consider it still relevant to a new CP2K version.

**Comment by jjlow** [comment]
Alfio,

This issue occurs with the development version of cp2k.  I needed to remove the "-align array64byte" flag to build cp2k.  So it is relevant.

It could improve performance of cp2k if resolved.  I think this issue is probably due to array alignment in either libint or libxc.

Perhaps it would be better if this issue was posted in the libint or libxc forums.

John Low

**Comment by hfp** [comment]
Hi John,

there may be spurious warnings for a (varying) set of object files generated during the final link stage of the Intel Compiler. During the KNC (not KNL) timeframe I digged into and concluded that these warnings may be (safely) ignored (these warnings exist independent of the compiler version).

However, all of the Intel compilers mentioned at [xconfigure.readthedocs.io/cp2k/README/](xconfigure.readthedocs.io/cp2k/README/) produce builds that pass regression tests (except for *roughly* four cases where there is a disagreement on the error margin). It is key to use the `-fp-model` flag as mentioned in this reference, because then tests pass even if you supply a target flag that permits vector instructions (aka `-xSomething` or `-mSomething`). Lazy people can use `arch/Linux-x86-64-intelx.*` even for the non-Intel branch (one can use `wget` to download as mentioned in the reference). The slightly outgrown ARCH file(s) also maintain workarounds that were at least necessary with older/certain versions of the compiler.

The XCONFIGURE reference provides recipes for common/optional CP2K dependencies i.e., LIBXC, LIBINT, and ELPA.

**Comment by hfp** [comment]
The XCONFIGURE recipe for LIBINT uses `-align array64byte`. Since I used this recipe for building LIBINT (and running CP2K regtests), any issues with regression tests must be related to something else. Btw, the old LIBINT 1.x line (currently/still required by CP2K) is quite a beast since the build system is not suitable for cross-compilation. In turn, this may cause problems with unclean builds if you switch between different hosts when you build LIBINT (aka KNL needs quite some time to compile).

Regarding your question (if it hurts on KNL), I have not done such an experiment (with/without array64byte). Also, proper alignment may only help if the leading dimensions (for multidimensional arrays) essentially again hit a proper alignment. I do think that `array64byte` makes a general impact. Overall, I believe CP2K seldomly benefits from vectorizing the regular code base wrt wall-time. Perhaps there are some speedups due to code vectorization in singluar cases but they have to make a hotspot (overall CP2K is quite a "big toolbox"). This is also because there is not much focus on flawless (auto-)vectorization (or directive based vectorization) for the generic code base. Vectorization in CP2K mostly left up to specialized libraries rather than spoiling the straight (and portable) code base. On the other hand, the grid based code ("colocate/integrate") can be auto-tuned (perhaps you can find/ask for some guide), and special cases (e.g., with LIBINT-related stuff) may be unrolled/special-cased to permit better (compiler-)optimizations.

**Comment by jjlow** [comment]
Thanks Hans,  this is very helpful.

I will working with cp2k in the ALCF performance workshop at Argonne over the next couple of days.  Your response has been very timely.

John Low

**Comment by hfp** [comment]
Typo: I do think that array64byte makes a general impact.
-> I do not think that array64byte makes a general impact.

Feel also free to send a private message if you need further assistence.

**Comment by alazzaro** [comment]
Indeed, indeed. Actually, I don't do that. i.e. I always use -nogit...
