### ISSUE TITLE
Ready multi-GPU support

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#702]
There is a clear trend towards having multiple GPUs per node and users start asking for it.

While DBCSR and SIRIUS each on their own support multi-GPU, there is anecdotal evidence of [interference](https://github.com/cp2k/dbcsr/issues/205) between them.

Unfortunately, we don't have a multi GPU dashboard test yet. The reason is that I first want to finish rewriting the [do_regtest](https://github.com/cp2k/cp2k/blob/master/tools/regtesting/do_regtest) script in order to mitigate the startup overhead for libcusmm's JIT compilation.

In the mid-term we should also add support for multiple GPUs per MPI rank.

**Comment by jtyang-chem** [comment]
Hi oschuett，

I'm very grateful to you developers's efforts on CP2K, it's truly a powerful soft, and this issue is really a good news!

Here is a little question, if I can specify the GPU serial numbers with the version now(like 7.1)? 

You see, I have 2 GPUs on one node, but if I run cp2k, all jobs will use the same one GPU, soon memory would run out and the other one GPU would just looking.

Could I avoid this waste of resource?

**Comment by oschuett** [comment]
@jtyang-chem, unfortunately I can't give you an answer, because I haven't yet found the time to look into mulit-GPU.

Generally, user questions like yours are best taken to our [forum](https://www.cp2k.org/howto:forum), where you can reach a larger audience.

**Comment by jtyang-chem** [comment]
@oschuett 
Thanks for the reply, I just afraid of no one will get an answer except you developers, next time I'll post to the forum, anyway, it's good to know it will be solved, thank you oschuett :)

**Comment by alazzaro** [comment]
@jtyang-chem I've just committed a version of CP2K which should solve the problem you reported of CP2K running on a single GPU. Please, use 2 (or multiple) ranks to use 2 GPUs.

**Comment by jtyang-chem** [comment]
@alazzaro GREAT! sorry for late reply, and thanks for your work, it gonna help a lot of people like me!

**Comment by alazzaro** [comment]
This problem is solved.
