### ISSUE TITLE
Pseudoatoms with fractional proton numbers?

### ISSUE THREAD

**Issue by anneb101** [cp2k/cp2k#839]
Hello CP2K developers,
I was reading a paper (Phys Rev Let. 120, 246801 (2018)) in which a biased counter-electrode for an electrochemical cell was modeled using Ne pseudoatoms with fractional proton numbers. Is it possible to model such pseudoatoms in a CP2K AIMD run? Could not find something like this from a search; any help is greatly appreciated.

**Comment by mkrack** [comment]
Hi

the cell charge is currently implemented only as a whole number in CP2K and thus a fractional cell charge is not supported by CP2K.

Matthias

**Comment by anneb101** [comment]
Thank you for your reply. To clarify, in the paper, they also compensate
each Ne pseudoatom's fractional proton with a fractional valence electron.
This gave a net zero cell charge. However, their method allows for charge
separation across 2 electrodes, something typically not possible in AIMD.
This being an unconventional technique, would there be anything similar
that could be done in CP2K?

**Comment by mkrack** [comment]
Again, a fractional cell compensation charge is not yet implemented in CP2K. It is possible, of course, that somebody is working on such techniques in CP2K, but I am not aware of such an activity.

Matthias

**Comment by mattatlincoln** [comment]
There are some options to do roughly what you want - though this should be on the user forum rather than dev list.

You can add fractional core charges
https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/SUBSYS/KIND.html#list_CORE_CORRECTION
but number of electrons doesn't change - you will get states shifted from a normal atom. You can add balanced charges to either side of your cell or psuedo hydrogens etc.

(You can apply an electric field through the (periodic) efield keywords or through the boundary conditions of the poisson solver.




                       
                        
The University of Lincoln, located in the heart of the city of Lincoln, has established an international reputation based on high student satisfaction, excellent graduate employment and world-class research.​
                         
The information in this e-mail and any attachments may be confidential. If you have received this email in error please notify the sender immediately and remove it from your system. Do not disclose the contents to another person or take copies.
​
Email is not secure and may contain viruses. The University of Lincoln makes every effort to ensure email is sent without viruses, but cannot guarantee this and recommends recipients take appropriate precautions.
​
The University may monitor email traffic data and content in accordance with its policies and English law. Further information can be found at: http://www.lincoln.ac.uk/legal. 
________________________________

**Comment by anneb101** [comment]
Thanks Matt, I apologize, I did not realize there was a forum and will use it for new use-related issues from now on. Since we are on this thread - I just wanted to clarify what is meant by "You can add balanced charges to either side of your cell" - is this something possible in tandem with fractional proton charge to balance it out, and what keyword should be used?

**Comment by mattatlincoln** [comment]
Hi, no problem, but it is better if questions like this can be seen by other users.

You can put the core correction with say +0.1 on atoms at the bottom of a slab setup and -0.1 on atoms on the other to get a net neutral charge but a field across. You don't actually need a neutral cell - charged cells are used in the literature.

Matt

                       
                        
The University of Lincoln, located in the heart of the city of Lincoln, has established an international reputation based on high student satisfaction, excellent graduate employment and world-class research.​
                         
The information in this e-mail and any attachments may be confidential. If you have received this email in error please notify the sender immediately and remove it from your system. Do not disclose the contents to another person or take copies.
​
Email is not secure and may contain viruses. The University of Lincoln makes every effort to ensure email is sent without viruses, but cannot guarantee this and recommends recipients take appropriate precautions.
​
The University may monitor email traffic data and content in accordance with its policies and English law. Further information can be found at: http://www.lincoln.ac.uk/legal. 
________________________________

**Comment by anneb101** [comment]
Thank you; I will explore that method for now!
