### ISSUE TITLE
CP2K does not compile with GCC 10.1

### ISSUE THREAD

**Issue by fxcoudert** [cp2k/cp2k#969]
Compiling CP2K 6.1 with GCC 10.1 on macOS fails with:

```
/private/tmp/cp2k-20200626-95234-k793x1/cp2k-6.1/src/common/mathlib.F:400:33:
  400 |          CALL dsyev("V", "U", n, a, n, eigval, work, lwork, info)
      |                                 1
......
 1032 |       CALL dsyev('V', 'U', n, a(1, 1), n, eig(1), work(1), lwork, info)
      |                              2   
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-2)
```

I know this is not the latest version, but this part of the code in master appears unchanged, so I think the issue will be valid with 7.1 and master as well.

**Comment by oschuett** [comment]
Thanks for reporting. This is a known problem with GCC 10.1, which is being worked on (#962).

**Comment by dev-zero** [comment]
btw, this is not an actual issue since on the calling level of functions Fortran passes a pointer to a double/float/complex/whatever. As long as the size of the storage the pointer references matches what blas/lapack/scalapack is accessing everything works.
What gfortran-10 does is to verify that the call signatures for implicitly defined (`external`) functions matches throughout a compilation unit.

**Comment by mbanck** [comment]
I'm still seeing a build failure in `src/qs_collocate_density.F ` on C2PK-7.1 (that code has since been rewritten in master):

```
mpif90 -c -g -Wall -O2 -funroll-loops -ftree-vectorize -ffree-form -ffree-line-length-none -D__GFORTRAN -D__FFTSG -D__FFTW3  -D__LIBINT -D__LIBXC -D__SPGLIB -D__parallel -D__BLACS -D__SCALAPACK -D__ELPA=201605 -I/usr/include/elpa/modules/ -I/usr/include/elpa/elpa/ -I/usr/include -D__COMPILE_ARCH="\"Linux-x86_64-gfortran\"" -D__COMPILE_DATE="\"Sat Oct  3 14:41:23 UTC 2020\"" -D__COMPILE_HOST="\"kohn\"" -D__COMPILE_REVISION="\"git:e635599\"" -D__DATA_DIR="\"/usr/share/cp2k\"" -D__SHORT_FILE__="\"qs_collocate_density.F\"" -I'/build/cp2k-BGzMwj/cp2k-7.1/src/' -I'/build/cp2k-BGzMwj/cp2k-7.1/obj/Linux-x86_64-gfortran/popt/exts/dbcsr' qs_collocate_density.F90 
/build/cp2k-BGzMwj/cp2k-7.1/src/qs_collocate_density.F:1939:23:

 1924 |                   CALL daxpy(nxy*(1 + ub - lb), 1.0_dp, lgrid%r(lbr, n), 1, lgrid%r(lbw, nw), 1)
      |                                                                            2
......
 1939 |                        rs_rho(igrid_level)%rs_grid%r(:, :, lb:ub), 1)
      |                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-3)
make[5]: *** [/build/cp2k-BGzMwj/cp2k-7.1/Makefile:466: qs_collocate_density.o] Error 1
make[4]: *** [/build/cp2k-BGzMwj/cp2k-7.1/Makefile:134: all] Error 2
```

Would be a candidate for a fix on the `support/7.1` branch?

**Comment by mtaillefumier** [comment]
To fix this you can just add this option `-fallow-argument-mismatch`  to the Fortran FLAGS variable. This is a mismatch between the declaration of the function and actual function call. As the code is written, the arguments are scalar but the function declaration expect an array. That's why gcc is complaining.

**Comment by mbanck** [comment]
Fair enough, but AFAICT the other occurrences of this were fixed in the code, so I wondered whether that might happen on the 7.1 branch as well. Good point in just going ahead with that workaround though.
